class PokemonMove:
    def __init__(self, name, move_type, category, power, accuracy, pp, effect=None, effect_prob=None):
        self.name = name
        self.move_type = move_type
        self.category = category
        self.power = power
        self.accuracy = accuracy
        self.pp = pp
        self.effect = effect
        self.effect_prob = effect_prob

    def __repr__(self):
        return (f"PokemonMove(name={self.name}, type={self.move_type}, "
                f"category={self.category}, power={self.power}, "
                f"accuracy={self.accuracy}, pp={self.pp}, "
                f"effect={self.effect}, effect_prob={self.effect_prob})")

# Lista de movimentos extraídos do PDF
moves = [
    PokemonMove("10,000,000 Volt Thunderbolt", "Electric", "Special", 195, None, 1, "High critical hit ratio"),
    PokemonMove("Absorb", "Grass", "Special", 20, 100, 25, "User recovers half the HP inflicted on opponent"),
    PokemonMove("Accelerock", "Rock", "Physical", 40, 100, 20, "User attacks first"),
    PokemonMove("Acid", "Poison", "Special", 40, 100, 30, "May lower opponent's Special Defense", 10),
    PokemonMove("Acid Armor", "Poison", "Status", None, None, 20, "Sharply raises user's Defense"),
    PokemonMove("Acid Downpour", "Poison", "Physical", None, None, 1, "Poison type Z-Move"),
    PokemonMove("Acid Spray", "Poison", "Special", 40, 100, 20, "Sharply lowers opponent's Special Defense", 100),
    PokemonMove("Acrobatics", "Flying", "Physical", 55, 100, 15, "Stronger when the user does not have a held item"),
    PokemonMove("Acupressure", "Normal", "Status", None, None, 30, "Sharply raises a random stat"),
    PokemonMove("Aerial Ace", "Flying", "Physical", 60, None, 20, "Ignores Accuracy and Evasiveness"),
    PokemonMove("Aeroblast", "Flying", "Special", 100, 95, 5, "High critical hit ratio"),
    PokemonMove("After You", "Normal", "Status", None, None, 15, "Gives target priority in the next turn"),
    PokemonMove("Agility", "Psychic", "Status", None, None, 30, "Sharply raises user's Speed"),
    PokemonMove("Air Cutter", "Flying", "Special", 60, 95, 25, "High critical hit ratio"),
    PokemonMove("Air Slash", "Flying", "Special", 75, 95, 15, "May cause flinching", 30),
    PokemonMove("All-Out Pummeling", "Fighting", "Physical", None, None, 1, "Fighting type Z-Move"),
    PokemonMove("Alluring Voice", "Fairy", "Special", 80, 100, 10),
    PokemonMove("Ally Switch", "Psychic", "Status", None, None, 15, "User switches with opposite teammate"),
    PokemonMove("Amnesia", "Psychic", "Status", None, None, 20, "Sharply raises user's Special Defense"),
    PokemonMove("Anchor Shot", "Steel", "Physical", 80, 100, 20, "The user entangles the target with its anchor chain while attacking. The target becomes unable to flee"),
    PokemonMove("Ancient Power", "Rock", "Special", 60, 100, 5, "May raise all user's stats at once", 10),
    PokemonMove("Apple Acid", "Grass", "Special", 80, 100, 10, "Lowers target's Special Defense", 100),
    PokemonMove("Aqua Cutter", "Water", "Physical", 70, 100, 20, "High critical hit ratio"),
    PokemonMove("Aqua Jet", "Water", "Physical", 40, 100, 20, "User attacks first"),
    PokemonMove("Aqua Ring", "Water", "Status", None, None, 20, "Restores a little HP each turn"),
    PokemonMove("Aqua Step", "Water", "Physical", 80, 100, 10, "Raises user's Speed", 100),
    PokemonMove("Aqua Tail", "Water", "Physical", 90, 90, 10),
    PokemonMove("Arm Thrust", "Fighting", "Physical", 15, 100, 20, "Hits 2-5 times in one turn"),
    PokemonMove("Armor Cannon", "Fire", "Special", 120, 100, 5, "Lowers user's Defense and Special Defense"),
    PokemonMove("Aromatherapy", "Grass", "Status", None, None, 5, "Cures all status problems in your party"),
    PokemonMove("Aromatic Mist", "Fairy", "Status", None, None, 20, "Raises Special Defense of an ally"),
    PokemonMove("Assist", "Normal", "Status", None, None, 20, "User performs a move known by its allies at random"),
    PokemonMove("Assurance", "Dark", "Physical", 60, 100, 10, "Power doubles if opponent already took damage in the same turn"),
    PokemonMove("Astonish", "Ghost", "Physical", 30, 100, 15, "May cause flinching", 30),
    PokemonMove("Astral Barrage", "Ghost", "Special", 120, 100, 5, "The user attacks by sending a frightful amount of small ghosts at opposing Pokémon"),
    PokemonMove("Attack Order", "Bug", "Physical", 90, 100, 15, "High critical hit ratio"),
    PokemonMove("Attract", "Normal", "Status", None, 100, 15, "If opponent is the opposite gender, it's less likely to attack"),
    PokemonMove("Aura Sphere", "Fighting", "Special", 80, None, 20, "Ignores Accuracy and Evasiveness"),
    PokemonMove("Aura Wheel", "Electric", "Physical", 110, 100, 10, "Changes type based on Morpeko's Mode", 100),
    PokemonMove("Aurora Beam", "Ice", "Special", 65, 100, 20, "May lower opponent's Attack", 10),
    PokemonMove("Aurora Veil", "Ice", "Status", None, None, 20, "Halves damage from Physical and Special attacks for five turns"),
    PokemonMove("Autotomize", "Steel", "Status", None, None, 15, "Reduces weight and sharply raises Speed"),
    PokemonMove("Avalanche", "Ice", "Physical", 60, 100, 10, "Power doubles if user took damage first"),
    PokemonMove("Axe Kick", "Fighting", "Physical", 120, 90, 10, "May confuse opponent. If it misses, the user loses HP"),
    PokemonMove("Baby-Doll Eyes", "Fairy", "Status", None, 100, 30, "Always goes first. Lowers the target's attack"),
    PokemonMove("Baddy Bad", "Dark", "Special", 90, 100, 15, "Reduces damage from Physical attacks"),
    PokemonMove("Baneful Bunker", "Poison", "Status", None, None, 10, "Protects the user and poisons opponent on contact"),
    PokemonMove("Barb Barrage", "Poison", "Physical", 60, 100, 10, "May poison opponent; inflicts double damage if the target is already poisoned"),
    PokemonMove("Barrage", "Normal", "Physical", 15, 85, 20, "Hits 2-5 times in one turn"),
    PokemonMove("Barrier", "Psychic", "Status", None, None, 20, "Sharply raises user's Defense"),
    PokemonMove("Baton Pass", "Normal", "Status", None, None, 40, "User switches out and gives stat changes to the incoming Pokémon"),
    PokemonMove("Beak Blast", "Flying", "Physical", 100, 100, 15, "The user first heats up its beak, then attacks. Direct contact while heating results in a burn"),
    PokemonMove("Beat Up", "Dark", "Physical", None, 100, 10, "Each Pokémon in user's party attacks"),
    PokemonMove("Behemoth Bash", "Steel", "Physical", 100, 100, 5, "Damage doubles if target is Dynamaxed"),
    PokemonMove("Behemoth Blade", "Steel", "Physical", 100, 100, 5, "Damage doubles if target is Dynamaxed"),
    PokemonMove("Belch", "Poison", "Special", 120, 90, 10, "User must have consumed a Berry"),
    PokemonMove("Belly Drum", "Normal", "Status", None, None, 10, "User loses 50% of its max HP, but Attack raises to maximum"),
    PokemonMove("Bestow", "Normal", "Status", None, None, 15, "Gives the user's held item to the target"),
    PokemonMove("Bide", "Normal", "Physical", None, None, 10, "User takes damage for two turns then strikes back double"),
    PokemonMove("Bind", "Normal", "Physical", 15, 85, 20, "Traps opponent, damaging them for 4-5 turns", 100),
    PokemonMove("Bite", "Dark", "Physical", 60, 100, 25, "May cause flinching", 30),
    PokemonMove("Bitter Blade", "Fire", "Physical", 90, 100, 10, "User recovers half the HP inflicted on opponent"),
    PokemonMove("Bitter Malice", "Ghost", "Special", 75, 100, 10, "Lowers opponent's Attack"),
    PokemonMove("Black Hole Eclipse", "Dark", "Special", None, None, 1, "Dark type Z-Move"),
    PokemonMove("Blast Burn", "Fire", "Special", 150, 90, 5, "User must recharge next turn"),
    PokemonMove("Blaze Kick", "Fire", "Physical", 85, 90, 10, "High critical hit ratio. May burn opponent", 10),
    PokemonMove("Blazing Torque", "Fire", "Physical", 80, 100, 10, "May burn the opponent"),
    PokemonMove("Bleakwind Storm", "Flying", "Special", 100, 80, 10, "May lower opponent's Speed"),
    PokemonMove("Blizzard", "Ice", "Special", 110, 70, 5, "May freeze opponent", 10),
    PokemonMove("Block", "Normal", "Status", None, None, 5, "Opponent cannot flee or switch"),
    PokemonMove("Blood Moon", "Normal", "Special", 140, 100, 5, "Cannot be used twice in a row"),
    PokemonMove("Bloom Doom", "Grass", "Special", None, None, 1, "Grass type Z-Move"),
    PokemonMove("Blue Flare", "Fire", "Special", 130, 85, 5, "May burn opponent", 20),
    PokemonMove("Body Press", "Fighting", "Physical", 80, 100, 10, "The higher the user's Defense, the stronger the attack"),
    PokemonMove("Body Slam", "Normal", "Physical", 85, 100, 15, "May paralyze opponent", 30),
    PokemonMove("Bolt Beak", "Electric", "Physical", 85, 100, 10, "If the user attacks before the target, the power of this move is doubled"),
    PokemonMove("Bolt Strike", "Electric", "Physical", 130, 85, 5, "May paralyze opponent", 20),
    PokemonMove("Bone Club", "Ground", "Physical", 65, 85, 20, "May cause flinching", 10),
    PokemonMove("Bone Rush", "Ground", "Physical", 25, 90, 10, "Hits 2-5 times in one turn"),
    PokemonMove("Bonemerang", "Ground", "Physical", 50, 90, 10, "Hits twice in one turn"),
    PokemonMove("Boomburst", "Normal", "Special", 140, 100, 10, "Hits all adjacent Pokémon"),
    PokemonMove("Bounce", "Flying", "Physical", 85, 85, 5, "Springs up on first turn, attacks on second. May paralyze opponent", 30),
    PokemonMove("Bouncy Bubble", "Water", "Special", 90, 100, 15, "User recovers half the HP inflicted on opponent"),
    PokemonMove("Branch Poke", "Grass", "Physical", 40, 100, 40),
    PokemonMove("Brave Bird", "Flying", "Physical", 120, 100, 15, "User receives recoil damage"),
    PokemonMove("Breaking Swipe", "Dragon", "Physical", 60, 100, 15, "Hits multiple opponents and lowers their attack", 100),
    PokemonMove("Breakneck Blitz", "Normal", "Physical", None, None, 1, "Normal type Z-Move"),
    PokemonMove("Brick Break", "Fighting", "Physical", 75, 100, 15, "Breaks through Reflect and Light Screen barriers"),
    PokemonMove("Brine", "Water", "Special", 65, 100, 10, "Power doubles if opponent's HP is less than 50%"),
    PokemonMove("Brutal Swing", "Dark", "Physical", 60, 100, 20, "The user swings its body around violently to inflict damage on everything in its vicinity"),
    PokemonMove("Bubble", "Water", "Special", 40, 100, 30, "May lower opponent's Speed", 10),
    PokemonMove("Bubble Beam", "Water", "Special", 65, 100, 20, "May lower opponent's Speed", 10),
    PokemonMove("Bug Bite", "Bug", "Physical", 60, 100, 20, "Receives the effect from the opponent's held berry"),
    PokemonMove("Bug Buzz", "Bug", "Special", 90, 100, 10, "May lower opponent's Special Defense", 10),
    PokemonMove("Bulk Up", "Fighting", "Status", None, None, 20, "Raises user's Attack and Defense"),
    PokemonMove("Bulldoze", "Ground", "Physical", 60, 100, 20, "Lowers opponent's Speed", 100),
    PokemonMove("Bullet Punch", "Steel", "Physical", 40, 100, 30, "User attacks first"),
    PokemonMove("Bullet Seed", "Grass", "Physical", 25, 100, 30, "Hits 2-5 times in one turn"),
    PokemonMove("Burn Up", "Fire", "Special", 130, 100, 5, "To inflict massive damage, the user burns itself out. After using this move, the user will no longer be Fire type"),
    PokemonMove("Burning Bulwark", "Fire", "Status", None, None, 10),
    PokemonMove("Burning Jealousy", "Fire", "Special", 70, 100, 5, "Hits all opponents, and burns any that have had their stats boosted"),
    PokemonMove("Buzzy Buzz", "Electric", "Special", 90, 100, 15, "Paralyzes the opponent", 100),
    PokemonMove("Calm Mind", "Psychic", "Status", None, None, 20, "Raises user's Special Attack and Special Defense"),
    PokemonMove("Camouflage", "Normal", "Status", None, None, 20, "Changes user's type according to the location"),
    PokemonMove("Captivate", "Normal", "Status", None, 100, 20, "Sharply lowers opponent's Special Attack if opposite gender"),
    PokemonMove("Catastropika", "Electric", "Physical", 210, None, 1, "Pikachu-exclusive Z-Move"),
    PokemonMove("Ceaseless Edge", "Dark", "Physical", 65, 90, 15, "Sets up Spikes"),
    PokemonMove("Celebrate", "Normal", "Status", None, None, 40, "The Pokémon congratulates you on your special day. No battle effect"),
    PokemonMove("Charge", "Electric", "Status", None, None, 20, "Raises user's Special Defense and next Electric move's power increases"),
    PokemonMove("Charge Beam", "Electric", "Special", 50, 90, 10, "May raise user's Special Attack", 70),
    PokemonMove("Charm", "Fairy", "Status", None, 100, 20, "Sharply lowers opponent's Attack"),
    PokemonMove("Chatter", "Flying", "Special", 65, 100, 20, "Confuses opponent", 100),
    PokemonMove("Chilling Water", "Water", "Special", 50, 100, 20, "Lowers opponent's Attack"),
    PokemonMove("Chilly Reception", "Ice", "Status", None, None, 10, "Switches out and summons a snowstorm lasting 5 turns"),
    PokemonMove("Chip Away", "Normal", "Physical", 70, 100, 20, "Ignores opponent's stat changes"),
    PokemonMove("Chloroblast", "Grass", "Special", 150, 95, 5, "User receives recoil damage"),
    PokemonMove("Circle Throw", "Fighting", "Physical", 60, 90, 10, "In battles, the opponent switches. In the wild, the Pokémon runs"),
    PokemonMove("Clamp", "Water", "Physical", 35, 85, 15, "Traps opponent, damaging them for 4-5 turns", 100),
    PokemonMove("Clanging Scales", "Dragon", "Special", 110, 100, 5, "Lowers user's Defense", 100),
    PokemonMove("Clangorous Soul", "Dragon", "Status", None, None, 5, "Raises all user's stats but loses HP", 100),
    PokemonMove("Clangorous Soulblaze", "Dragon", "Special", 185, None, 1, "Kommo-o exclusive Z-Move"),
    PokemonMove("Clear Smog", "Poison", "Special", 50, None, 15, "Removes all of the target's stat changes"),
    PokemonMove("Close Combat", "Fighting", "Physical", 120, 100, 5, "Lowers user's Defense and Special Defense", 100),
    PokemonMove("Coaching", "Fighting", "Status", None, None, 10, "Boosts Attack and Defense of a teammate"),
    PokemonMove("Coil", "Poison", "Status", None, None, 20, "Raises user's Attack, Defense and Accuracy"),
    PokemonMove("Collision Course", "Fighting", "Physical", 100, 100, 5, "Boosted even more if it's super-effective"),
    PokemonMove("Combat Torque", "Fighting", "Physical", 100, 100, 10, "May paralyze the opponent"),
    PokemonMove("Comet Punch", "Normal", "Physical", 18, 85, 15, "Hits 2-5 times in one turn"),
    PokemonMove("Comeuppance", "Dark", "Physical", None, 100, 10, "Deals more damage to the opponent that last inflicted damage on it"),
    PokemonMove("Confide", "Normal", "Status", None, None, 20, "Lowers opponent's Special Attack", 100),
    PokemonMove("Confuse Ray", "Ghost", "Status", None, 100, 10, "Confuses opponent"),
    PokemonMove("Confusion", "Psychic", "Special", 50, 100, 25, "May confuse opponent", 10),
    PokemonMove("Constrict", "Normal", "Physical", 10, 100, 35, "May lower opponent's Speed", 10),
    PokemonMove("Continental Crush", "Rock", "Physical", None, None, 1, "Rock type Z-Move"),
    PokemonMove("Conversion", "Normal", "Status", None, None, 30, "Changes user's type to that of its first move"),
    PokemonMove("Conversion 2", "Normal", "Status", None, None, 30, "User changes type to become resistant to opponent's last move"),
    PokemonMove("Copycat", "Normal", "Status", None, None, 20, "Copies opponent's last move"),
    PokemonMove("Core Enforcer", "Dragon", "Special", 100, 100, 10, "Suppresses the target's ability if the target has already moved"),
    PokemonMove("Corkscrew Crash", "Steel", "Physical", None, None, 1, "Steel type Z-Move"),
    PokemonMove("Corrosive Gas", "Poison", "Status", None, 100, 40, "Removes opponent's items"),
    PokemonMove("Cosmic Power", "Psychic", "Status", None, None, 20, "Raises user's Defense and Special Defense"),
    PokemonMove("Cotton Guard", "Grass", "Status", None, None, 10, "Drastically raises user's Defense"),
    PokemonMove("Cotton Spore", "Grass", "Status", None, 100, 40, "Sharply lowers opponent's Speed"),
    PokemonMove("Counter", "Fighting", "Physical", None, 100, 20, "When hit by a Physical Attack, user strikes back with 2x power"),
    PokemonMove("Court Change", "Normal", "Status", None, 100, 10, "Swaps the effects on either side of the field"),
    PokemonMove("Covet", "Normal", "Physical", 60, 100, 25, "Opponent's item is stolen by the user"),
    PokemonMove("Crabhammer", "Water", "Physical", 100, 90, 10, "High critical hit ratio"),
    PokemonMove("Crafty Shield", "Fairy", "Status", None, None, 10, "Protects the Pokémon from status moves"),
    PokemonMove("Cross Chop", "Fighting", "Physical", 100, 80, 5, "High critical hit ratio"),
    PokemonMove("Cross Poison", "Poison", "Physical", 70, 100, 20, "High critical hit ratio. May poison opponent", 10),
    PokemonMove("Crunch", "Dark", "Physical", 80, 100, 15, "May lower opponent's Defense", 20),
    PokemonMove("Crush Claw", "Normal", "Physical", 75, 95, 10, "May lower opponent's Defense", 50),
    PokemonMove("Crush Grip", "Normal", "Physical", None, 100, 5, "More powerful when opponent has higher HP"),
    PokemonMove("Curse", "Ghost", "Status", None, None, 10, "Ghosts lose 50% of max HP and curse the opponent; Non-Ghosts raise Attack, Defense and lower Speed"),
    PokemonMove("Cut", "Normal", "Physical", 50, 95, 30),
    PokemonMove("Dark Pulse", "Dark", "Special", 80, 100, 15, "May cause flinching", 20),
    PokemonMove("Dark Void", "Dark", "Status", None, 50, 10, "Puts all adjacent opponents to sleep"),
    PokemonMove("Darkest Lariat", "Dark", "Physical", 85, 100, 10, "Ignores opponent's stat changes"),
    PokemonMove("Dazzling Gleam", "Fairy", "Special", 80, 100, 10, "Hits all adjacent opponents"),
    PokemonMove("Decorate", "Fairy", "Status", None, None, 15, "Sharply raises target's Attack and Special Attack", 100),
    PokemonMove("Defend Order", "Bug", "Status", None, None, 10, "Raises user's Defense and Special Defense"),
    PokemonMove("Defense Curl", "Normal", "Status", None, None, 40, "Raises user's Defense"),
    PokemonMove("Defog", "Flying", "Status", None, None, 15, "Lowers opponent's Evasiveness and clears fog"),
    PokemonMove("Destiny Bond", "Ghost", "Status", None, None, 5, "If the user faints, the opponent also faints"),
    PokemonMove("Detect", "Fighting", "Status", None, None, 5, "Protects the user, but may fail if used consecutively"),
    PokemonMove("Devastating Drake", "Dragon", "Special", None, None, 1, "Dragon type Z-Move"),
    PokemonMove("Diamond Storm", "Rock", "Physical", 100, 95, 5, "May sharply raise user's Defense", 50),
    PokemonMove("Dig", "Ground", "Physical", 80, 100, 10, "Digs underground on first turn, attacks on second. Can also escape from caves"),
    PokemonMove("Dire Claw", "Poison", "Physical", 80, 100, 15, "May poison, paralyze or put the opponent to sleep"),
    PokemonMove("Disable", "Normal", "Status", None, 100, 20, "Opponent can't use its last attack for a few turns"),
    PokemonMove("Disarming Voice", "Fairy", "Special", 40, None, 15, "Ignores Accuracy and Evasiveness"),
    PokemonMove("Discharge", "Electric", "Special", 80, 100, 15, "May paralyze opponent", 30),
    PokemonMove("Dive", "Water", "Physical", 80, 100, 10, "Dives underwater on first turn, attacks on second turn"),
    PokemonMove("Dizzy Punch", "Normal", "Physical", 70, 100, 10, "May confuse opponent", 20),
    PokemonMove("Doodle", "Normal", "Status", None, 100, 10, "Changes the abilities of the user and its teammates to that of the target"),
    PokemonMove("Doom Desire", "Steel", "Special", 140, 100, 5, "Damage occurs 2 turns later"),
    PokemonMove("Double Hit", "Normal", "Physical", 35, 90, 10, "Hits twice in one turn"),
    PokemonMove("Double Iron Bash", "Steel", "Physical", 60, 100, 5, "Hits twice in one turn; may cause flinching", 30),
    PokemonMove("Double Kick", "Fighting", "Physical", 30, 100, 30, "Hits twice in one turn"),
    PokemonMove("Double Shock", "Electric", "Physical", 120, 100, 5, "After using this move, the user will no longer be Electric type"),
    PokemonMove("Double Slap", "Normal", "Physical", 15, 85, 10, "Hits 2-5 times in one turn"),
    PokemonMove("Double Team", "Normal", "Status", None, None, 15, "Raises user's Evasiveness"),
    PokemonMove("Double-Edge", "Normal", "Physical", 120, 100, 15, "User receives recoil damage"),
    PokemonMove("Draco Meteor", "Dragon", "Special", 130, 90, 5, "Sharply lowers user's Special Attack", 100),
    PokemonMove("Dragon Ascent", "Flying", "Physical", 120, 100, 5, "Lowers user's Defense and Special Defense", 100),
    PokemonMove("Dragon Breath", "Dragon", "Special", 60, 100, 20, "May paralyze opponent", 30),
    PokemonMove("Dragon Cheer", "Dragon", "Status", None, None, 15),
    PokemonMove("Dragon Claw", "Dragon", "Physical", 80, 100, 15),
    PokemonMove("Dragon Dance", "Dragon", "Status", None, None, 20, "Raises user's Attack and Speed"),
    PokemonMove("Dragon Darts", "Dragon", "Physical", 50, 100, 10, "User attacks twice"),
    PokemonMove("Dragon Energy", "Dragon", "Special", 150, 100, 5, "The higher the user's HP, the higher the power"),
    PokemonMove("Dragon Hammer", "Dragon", "Physical", 90, 100, 15, "The user uses its body like a hammer to attack the target and inflict damage"),
    PokemonMove("Dragon Pulse", "Dragon", "Special", 85, 100, 10),
    PokemonMove("Dragon Rage", "Dragon", "Special", None, 100, 10, "Always inflicts 40 HP"),
    PokemonMove("Dragon Rush", "Dragon", "Physical", 100, 75, 10, "May cause flinching", 20),
    PokemonMove("Dragon Tail", "Dragon", "Physical", 60, 90, 10, "In battles, the opponent switches. In the wild, the Pokémon runs"),
    PokemonMove("Drain Punch", "Fighting", "Physical", 75, 100, 10, "User recovers half the HP inflicted on opponent"),
    PokemonMove("Draining Kiss", "Fairy", "Special", 50, 100, 10, "User recovers most of the HP inflicted on opponent"),
    PokemonMove("Dream Eater", "Psychic", "Special", 100, 100, 15, "User recovers half the HP inflicted on a sleeping opponent"),
    PokemonMove("Drill Peck", "Flying", "Physical", 80, 100, 20),
    PokemonMove("Drill Run", "Ground", "Physical", 80, 95, 10, "High critical hit ratio"),
    PokemonMove("Drum Beating", "Grass", "Physical", 80, 100, 10, "Lowers opponent's Speed", 100),
    PokemonMove("Dual Chop", "Dragon", "Physical", 40, 90, 15, "Hits twice in one turn"),
    PokemonMove("Dual Wingbeat", "Flying", "Physical", 40, 90, 10, "The user slams the target with its wings. The target is hit twice in a row"),
    PokemonMove("Dynamax Cannon", "Dragon", "Special", 100, 100, 5, "Damage doubles if opponent is Dynamaxed"),
    PokemonMove("Dynamic Punch", "Fighting", "Physical", 100, 50, 5, "Confuses opponent", 100),
    PokemonMove("Earth Power", "Ground", "Special", 90, 100, 10, "May lower opponent's Special Defense", 10),
    PokemonMove("Earthquake", "Ground", "Physical", 100, 100, 10, "Power is doubled if opponent is underground from using Dig"),
    PokemonMove("Echoed Voice", "Normal", "Special", 40, 100, 15, "Power increases each turn"),
    PokemonMove("Eerie Impulse", "Electric", "Status", None, 100, 15, "Sharply lowers opponent's Special Attack"),
    PokemonMove("Eerie Spell", "Psychic", "Special", 80, 100, 5, "Deals damage and reduces opponent's PP"),
    PokemonMove("Egg Bomb", "Normal", "Physical", 100, 75, 10),
    PokemonMove("Electric Terrain", "Electric", "Status", None, None, 10, "Prevents all Pokémon from falling asleep for 5 turns"),
    PokemonMove("Electrify", "Electric", "Status", None, None, 20, "Changes the target's move to Electric type"),
    PokemonMove("Electro Ball", "Electric", "Special", None, 100, 10, "The faster the user, the stronger the attack"),
    PokemonMove("Electro Drift", "Electric", "Special", 100, 100, 5, "Boosted even more if it's super-effective"),
    PokemonMove("Electro Shot", "Electric", "Physical", 130, 100, 10, "Charges on first turn, attacks on second"),
    PokemonMove("Electroweb", "Electric", "Special", 55, 95, 15, "Lowers opponent's Speed", 100),
    PokemonMove("Embargo", "Dark", "Status", None, 100, 15, "Opponent cannot use items"),
    PokemonMove("Ember", "Fire", "Special", 40, 100, 25, "May burn opponent", 10),
    PokemonMove("Encore", "Normal", "Status", None, 100, 5, "Forces opponent to keep using its last move for 3 turns"),
    PokemonMove("Endeavor", "Normal", "Physical", None, 100, 5, "Reduces opponent's HP to same as user's"),
    PokemonMove("Endure", "Normal", "Status", None, None, 10, "Always left with at least 1 HP, but may fail if used consecutively"),
    PokemonMove("Energy Ball", "Grass", "Special", 90, 100, 10, "May lower opponent's Special Defense", 10),
    PokemonMove("Entrainment", "Normal", "Status", None, 100, 15, "Makes target's ability same as user's"),
    PokemonMove("Eruption", "Fire", "Special", 150, 100, 5, "Stronger when the user's HP is higher"),
    PokemonMove("Esper Wing", "Psychic", "Special", 80, 100, 10, "High critical hit ratio. Raises user's Speed"),
    PokemonMove("Eternabeam", "Dragon", "Special", 160, 90, 5, "User can't move on the next turn"),
    PokemonMove("Expanding Force", "Psychic", "Special", 80, 100, 10, "Increases power and hits all opponents on Psychic Terrain"),
    PokemonMove("Explosion", "Normal", "Physical", 250, 100, 5, "User faints"),
    PokemonMove("Extrasensory", "Psychic", "Special", 80, 100, 20, "May cause flinching", 10),
    PokemonMove("Extreme Evoboost", "Normal", "Status", None, None, 1, "Eevee-exclusive Z-Move. Sharply raises all stats", 100),
    PokemonMove("Extreme Speed", "Normal", "Physical", 80, 100, 5, "User attacks first"),
    PokemonMove("Facade", "Normal", "Physical", 70, 100, 20, "Power doubles if user is burned, poisoned, or paralyzed"),
    PokemonMove("Fairy Lock", "Fairy", "Status", None, None, 10, "Prevents fleeing in the next turn"),
    PokemonMove("Fairy Wind", "Fairy", "Special", 40, 100, 30),
    PokemonMove("Fake Out", "Normal", "Physical", 40, 100, 10, "User attacks first, foe flinches. Only usable on first turn", 100),
    PokemonMove("Fake Tears", "Dark", "Status", None, 100, 20, "Sharply lowers opponent's Special Defense"),
    PokemonMove("False Surrender", "Dark", "Physical", 80, None, 10, "Ignores Accuracy and Evasiveness"),
    PokemonMove("False Swipe", "Normal", "Physical", 40, 100, 40, "Always leaves opponent with at least 1 HP"),
    PokemonMove("Feather Dance", "Flying", "Status", None, 100, 15, "Sharply lowers opponent's Attack"),
    PokemonMove("Feint", "Normal", "Physical", 30, 100, 10, "Only hits if opponent uses Protect or Detect in the same turn"),
    PokemonMove("Feint Attack", "Dark", "Physical", 60, None, 20, "Ignores Accuracy and Evasiveness"),
    PokemonMove("Fell Stinger", "Bug", "Physical", 50, 100, 25, "Drastically raises user's Attack if target is KO'd"),
    PokemonMove("Fickle Beam", "Dragon", "Special", 80, 100, 5, "May deal double damage"),
    PokemonMove("Fiery Dance", "Fire", "Special", 80, 100, 10, "May raise user's Special Attack", 50),
    PokemonMove("Fiery Wrath", "Dark", "Special", 90, 100, 10, "May cause flinching", 20),
    PokemonMove("Fillet Away", "Normal", "Status", None, None, 10, "Lowers HP but sharply boosts Attack, Special Attack, and Speed"),
    PokemonMove("Final Gambit", "Fighting", "Special", None, 100, 5, "Inflicts damage equal to the user's remaining HP. User faints"),
    PokemonMove("Fire Blast", "Fire", "Special", 110, 85, 5, "May burn opponent", 10),
    PokemonMove("Fire Fang", "Fire", "Physical", 65, 95, 15, "May cause flinching and/or burn opponent", 10),
    PokemonMove("Fire Lash", "Fire", "Physical", 80, 100, 15, "The user strikes the target with a burning lash. This also lowers the target's Defense", 100),
    PokemonMove("Fire Pledge", "Fire", "Special", 80, 100, 10, "Added effects appear if combined with Grass Pledge or Water Pledge"),
    PokemonMove("Fire Punch", "Fire", "Physical", 75, 100, 15, "May burn opponent", 10),
    PokemonMove("Fire Spin", "Fire", "Special", 35, 85, 15, "Traps opponent, damaging them for 4-5 turns", 100),
    PokemonMove("First Impression", "Bug", "Physical", 90, 100, 10, "Although this move has great power, it only works the first turn the user is in battle"),
    PokemonMove("Fishious Rend", "Water", "Physical", 85, 100, 10, "If the user attacks before the target, the power of this move is doubled"),
    PokemonMove("Fissure", "Ground", "Physical", None, 30, 5, "One-Hit-KO, if it hits"),
    PokemonMove("Flail", "Normal", "Physical", None, 100, 15, "The lower the user's HP, the higher the power"),
    PokemonMove("Flame Burst", "Fire", "Special", 70, 100, 15, "May also injure nearby Pokémon"),
    PokemonMove("Flame Charge", "Fire", "Physical", 50, 100, 20, "Raises user's Speed", 100),
    PokemonMove("Flame Wheel", "Fire", "Physical", 60, 100, 25, "May burn opponent", 10),
    PokemonMove("Flamethrower", "Fire", "Special", 90, 100, 15, "May burn opponent", 10),
    PokemonMove("Flare Blitz", "Fire", "Physical", 120, 100, 15, "User receives recoil damage. May burn opponent", 10),
    PokemonMove("Flash", "Normal", "Status", None, 100, 20, "Lowers opponent's Accuracy"),
    PokemonMove("Flash Cannon", "Steel", "Special", 80, 100, 10, "May lower opponent's Special Defense", 10),
    PokemonMove("Flatter", "Dark", "Status", None, 100, 15, "Confuses opponent, but raises its Special Attack"),
    PokemonMove("Fleur Cannon", "Fairy", "Special", 130, 90, 5, "Sharply lowers user's Special Attack", 100),
    PokemonMove("Fling", "Dark", "Physical", None, 100, 10, "Power depends on held item"),
    PokemonMove("Flip Turn", "Water", "Physical", 60, 100, 20, "After making its attack, the user rushes back to switch places with a party Pokémon in waiting"),
    PokemonMove("Floaty Fall", "Flying", "Physical", 90, 95, 15, "May cause flinching", 30),
    PokemonMove("Floral Healing", "Fairy", "Status", None, None, 10, "Restores the target's HP by up to half of its max HP. It restores more HP when on Grassy Terrain"),
    PokemonMove("Flower Shield", "Fairy", "Status", None, None, 10, "Raises the Defense of all Grass-type Pokémon in battle"),
    PokemonMove("Flurry Rush", "Ice", "Physical", 25, 100, 10, "Hits 2-5 times in one turn"),
    PokemonMove("Focus Blast", "Fighting", "Special", 120, 70, 5, "May lower opponent's Special Defense", 10),
    PokemonMove("Focus Energy", "Normal", "Status", None, None, 30, "Increases user's critical hit ratio"),
    PokemonMove("Focus Punch", "Fighting", "Physical", 150, 100, 20, "User loses its focus if hit before it attacks"),
    PokemonMove("Follow Me", "Normal", "Status", None, None, 20, "The user draws attention to itself, making all targets aim only at the user"),
    PokemonMove("Force Palm", "Fighting", "Physical", 60, 100, 10, "May paralyze opponent", 30),
    PokemonMove("Foresight", "Normal", "Status", None, None, 40, "Negates opponent's efforts to heighten evasiveness. Ghosts become vulnerable to Normal and Fighting moves"),
    PokemonMove("Forest's Curse", "Ghost", "Status", None, 100, 20, "Adds Grass type to the target"),
    PokemonMove("Foul Play", "Dark", "Physical", 95, 100, 15, "The higher the opponent's Attack, the more damage caused"),
    PokemonMove("Freeze-Dry", "Ice", "Special", 70, 100, 20, "May freeze opponent. Super-effective on Water types", 10),
    PokemonMove("Freeze Shock", "Ice", "Physical", 140, 90, 5, "Charges on first turn, attacks on second. May paralyze opponent", 30),
    PokemonMove("Freezing Glare", "Psychic", "Special", 90, 100, 10, "May freeze opponent", 10),
    PokemonMove("Freezy Frost", "Ice", "Special", 100, 95, 15, "Resets opponent's stat changes"),
    PokemonMove("Frenzy Plant", "Grass", "Special", 150, 90, 5, "User must recharge next turn"),
    PokemonMove("Frost Breath", "Ice", "Special", 60, 90, 10, "Always results in a critical hit"),
    PokemonMove("Frustration", "Normal", "Physical", None, 100, 20, "Power decreases with higher friendship"),
    PokemonMove("Fury Attack", "Normal", "Physical", 15, 85, 20, "Hits 2-5 times in one turn"),
    PokemonMove("Fury Cutter", "Bug", "Physical", 40, 95, 20, "Power increases each turn"),
    PokemonMove("Fury Swipes", "Normal", "Physical", 18, 80, 15, "Hits 2-5 times in one turn"),
    PokemonMove("Fusion Bolt", "Electric", "Physical", 100, 100, 5, "Power increases if Fusion Flare hits immediately before"),
    PokemonMove("Fusion Flare", "Fire", "Special", 100, 100, 5, "Power increases if Fusion Bolt hits immediately before"),
    PokemonMove("Future Sight", "Psychic", "Special", 120, 100, 10, "Attack hits two turns later"),
    PokemonMove("G-Max Befuddle", "Bug", "Special", None, None, 10, "Bug-type Dynamax move. Inflicts sleep, poison, or paralysis"),
    PokemonMove("G-Max Cannonade", "Water", "Special", None, None, 10, "Water-type Dynamax move. Deals damage for four turns"),
    PokemonMove("G-Max Centiferno", "Fire", "Special", None, None, 10, "Fire-type Dynamax move. Traps opponents for four turns"),
    PokemonMove("G-Max Chi Strike", "Fighting", "Physical", None, None, 10, "Fighting-type Dynamax move. Increases critical hit ratio"),
    PokemonMove("G-Max Cuddle", "Normal", "Physical", None, None, 10, "Normal-type Dynamax move. Opponents of the opposite gender become infatuated"),
    PokemonMove("G-Max Depletion", "Dragon", "Special", None, None, 10, "Dragon-type Dynamax move. Reduces opponent's PP"),
    PokemonMove("G-Max Finale", "Fairy", "Special", None, None, 10, "Fairy-type Dynamax move. Restores HP of allies"),
    PokemonMove("G-Max Fireball", "Fire", "Physical", None, None, 10, "Fire-type Dynamax move. Ignores effects of moves and abilities that draw in moves"),
    PokemonMove("G-Max Foam Burst", "Water", "Special", None, None, 10, "Water-type Dynamax move. Lowers Speed of opponents"),
    PokemonMove("G-Max Gold Rush", "Normal", "Special", None, None, 10, "Normal-type Dynamax move. Confuses opponents and earns extra money"),
    PokemonMove("G-Max Gravitas", "Psychic", "Special", None, None, 10, "Psychic-type Dynamax move. Grounds opponents"),
    PokemonMove("G-Max Hydrosnipe", "Water", "Physical", None, None, 10, "Water-type Dynamax move. Ignores effects of moves and abilities that draw in moves"),
    PokemonMove("G-Max Malodor", "Poison", "Special", None, None, 10, "Poison-type Dynamax move. Poisons opponents"),
    PokemonMove("G-Max Meltdown", "Steel", "Special", None, None, 10, "Steel-type Dynamax move. Prevents opponents from using the same move twice in a row"),
    PokemonMove("G-Max One Blow", "Dark", "Physical", None, None, 10, "Dark-type Dynamax move. Ignores Max Guard"),
    PokemonMove("G-Max Rapid Flow", "Water", "Physical", None, None, 10, "Water-type Dynamax move. Ignores Max Guard"),
    PokemonMove("G-Max Replenish", "Normal", "Physical", None, None, 10, "Normal-type Dynamax move. Restores consumed berries"),
    PokemonMove("G-Max Resonance", "Ice", "Special", None, None, 10, "Ice-type Dynamax move. Reduces damage for five turns"),
    PokemonMove("G-Max Sandblast", "Ground", "Physical", None, None, 10, "Ground-type Dynamax move. Traps opponents for four turns"),
    PokemonMove("G-Max Smite", "Fairy", "Special", None, None, 10, "Fairy-type Dynamax move. Confuses opponents"),
    PokemonMove("G-Max Snooze", "Dark", "Special", None, None, 10, "Dark-type Dynamax move. Opponents fall asleep after the turn ends"),
    PokemonMove("G-Max Steelsurge", "Steel", "Special", None, None, 10, "Steel-type Dynamax move. Scatters sharp objects around the field"),
    PokemonMove("G-Max Stonesurge", "Water", "Physical", None, None, 10, "Water-type Dynamax move. Scatters sharp objects around the field"),
    PokemonMove("G-Max Stun Shock", "Electric", "Special", None, None, 10, "Electric-type Dynamax move. Paralyzes or poisons opponents"),
    PokemonMove("G-Max Sweetness", "Grass", "Special", None, None, 10, "Grass-type Dynamax move. Cures status conditions of allies"),
    PokemonMove("G-Max Tartness", "Grass", "Physical", None, None, 10, "Grass-type Dynamax move. Increases critical hit ratio"),
    PokemonMove("G-Max Terror", "Ghost", "Physical", None, None, 10, "Ghost-type Dynamax move. Prevents opponents from fleeing"),
    PokemonMove("G-Max Vine Lash", "Grass", "Special", None, None, 10, "Grass-type Dynamax move. Deals damage for four turns"),
    PokemonMove("G-Max Volcalith", "Rock", "Special", None, None, 10, "Rock-type Dynamax move. Deals damage for four turns"),
    PokemonMove("G-Max Wildfire", "Fire", "Special", None, None, 10, "Fire-type Dynamax move. Deals damage for four turns"),
    PokemonMove("G-Max Wind Rage", "Flying", "Physical", None, None, 10, "Flying-type Dynamax move. Removes obstacles like Terrain and Entry Hazards"),
    PokemonMove("Gastro Acid", "Poison", "Status", None, 100, 10, "Neutralizes the opponent's ability"),
    PokemonMove("Gear Grind", "Steel", "Physical", 50, 85, 15, "Hits twice in one turn"),
    PokemonMove("Gear Up", "Steel", "Status", None, None, 20, "Boosts Attack and Special Attack of allies with Plus or Minus Ability"),
    PokemonMove("Genesis Supernova", "Psychic", "Special", 185, None, 1, "Mew-exclusive Z-Move. Turns the field into Psychic Terrain"),
    PokemonMove("Geomancy", "Fairy", "Status", None, None, 10, "Charges on first turn, sharply raises Special Attack, Special Defense, and Speed on second turn"),
    PokemonMove("Giga Drain", "Grass", "Special", 75, 100, 10, "User recovers half the HP inflicted on opponent"),
    PokemonMove("Giga Impact", "Normal", "Physical", 150, 90, 5, "User must recharge next turn"),
    PokemonMove("Gigaton Hammer", "Steel", "Physical", 160, 100, 5, "Cannot be used twice in a row"),
    PokemonMove("Glacial Lance", "Ice", "Physical", 130, 100, 5),
    PokemonMove("Glaciate", "Ice", "Special", 65, 95, 10, "Lowers opponent's Speed", 100),
    PokemonMove("Glare", "Normal", "Status", None, 100, 30, "Paralyzes opponent"),
    PokemonMove("Glitzy Glow", "Psychic", "Special", 80, 100, 15, "Sets up a light screen"),
    PokemonMove("Gloom Doom", "Grass", "Special", None, None, 1, "Grass-type Z-Move"),
    PokemonMove("G-Max Drum Solo", "Grass", "Physical", None, None, 10, "Grass-type Dynamax move. Ignores effects of moves and abilities that draw in moves"),
    PokemonMove("G-Max Fireball", "Fire", "Physical", None, None, 10, "Fire-type Dynamax move. Ignores effects of moves and abilities that draw in moves"),
    PokemonMove("G-Max Hydrosnipe", "Water", "Physical", None, None, 10, "Water-type Dynamax move. Ignores effects of moves and abilities that draw in moves"),
    PokemonMove("G-Max Meltdown", "Steel", "Special", None, None, 10, "Steel-type Dynamax move. Prevents opponents from using the same move twice in a row"),
    PokemonMove("G-Max Sweetness", "Grass", "Special", None, None, 10, "Grass-type Dynamax move. Cures status conditions of allies"),
    PokemonMove("G-Max Tartness", "Grass", "Physical", None, None, 10, "Grass-type Dynamax move. Increases critical hit ratio"),
    PokemonMove("G-Max Vine Lash", "Grass", "Special", None, None, 10, "Grass-type Dynamax move. Deals damage for four turns"),
    PokemonMove("G-Max Volcalith", "Rock", "Special", None, None, 10, "Rock-type Dynamax move. Deals damage for four turns"),
    PokemonMove("G-Max Wildfire", "Fire", "Special", None, None, 10, "Fire-type Dynamax move. Deals damage for four turns"),
    PokemonMove("G-Max Wind Rage", "Flying", "Physical", None, None, 10, "Flying-type Dynamax move. Removes obstacles like Terrain and Entry Hazards"),
    PokemonMove("Gastro Acid", "Poison", "Status", None, 100, 10, "Neutralizes the opponent's ability"),
    PokemonMove("Gear Grind", "Steel", "Physical", 50, 85, 15, "Hits twice in one turn"),
    PokemonMove("Gear Up", "Steel", "Status", None, None, 20, "Boosts Attack and Special Attack of allies with Plus or Minus Ability"),
    PokemonMove("Genesis Supernova", "Psychic", "Special", 185, None, 1, "Mew-exclusive Z-Move. Turns the field into Psychic Terrain"),
    PokemonMove("Geomancy", "Fairy", "Status", None, None, 10, "Charges on first turn, sharply raises Special Attack, Special Defense, and Speed on second turn"),
    PokemonMove("Giga Drain", "Grass", "Special", 75, 100, 10, "User recovers half the HP inflicted on opponent"),
    PokemonMove("Giga Impact", "Normal", "Physical", 150, 90, 5, "User must recharge next turn"),
    PokemonMove("Gigaton Hammer", "Steel", "Physical", 160, 100, 5, "Cannot be used twice in a row"),
    PokemonMove("Glacial Lance", "Ice", "Physical", 130, 100, 5),
    PokemonMove("Glaciate", "Ice", "Special", 65, 95, 10, "Lowers opponent's Speed", 100),
    PokemonMove("Glare", "Normal", "Status", None, 100, 30, "Paralyzes opponent"),
    PokemonMove("Glitzy Glow", "Psychic", "Special", 80, 100, 15, "Sets up a light screen"),
    PokemonMove("Gloom Doom", "Grass", "Special", None, None, 1, "Grass-type Z-Move"),
    PokemonMove("G-Max Drum Solo", "Grass", "Physical", None, None, 10, "Grass-type Dynamax move. Ignores effects of moves and abilities that draw in moves"),
    PokemonMove("Grassy Glide", "Grass", "Physical", 70, 100, 20, "User attacks first on Grassy Terrain"),
    PokemonMove("Grassy Terrain", "Grass", "Status", None, None, 10, "Restores a little HP to all Pokémon for 5 turns. Powers up Grass-type moves"),
    PokemonMove("Grav Apple", "Grass", "Physical", 80, 100, 10, "Lowers opponent's Defense", 100),
    PokemonMove("Gravity", "Psychic", "Status", None, None, 5, "Prevents moves like Fly and Bounce and lowers Evasiveness for 5 turns"),
    PokemonMove("Growl", "Normal", "Status", None, 100, 40, "Lowers opponent's Attack"),
    PokemonMove("Growth", "Normal", "Status", None, None, 20, "Raises user's Attack and Special Attack"),
    PokemonMove("Grudge", "Ghost", "Status", None, None, 5, "If the user faints, opponent's move loses all PP"),
    PokemonMove("Guard Split", "Psychic", "Status", None, None, 10, "Averages Defense and Special Defense with the target"),
    PokemonMove("Guard Swap", "Psychic", "Status", None, None, 10, "User swaps its Defense and Special Defense with the opponent"),
    PokemonMove("Guillotine", "Normal", "Physical", None, 30, 5, "One-Hit-KO, if it hits"),
    PokemonMove("Gunk Shot", "Poison", "Physical", 120, 80, 5, "May poison opponent", 30),
    PokemonMove("Gust", "Flying", "Special", 40, 100, 35, "Hits Pokémon using Fly or Bounce with double power"),
    PokemonMove("Gyro Ball", "Steel", "Physical", None, 100, 5, "The slower the user compared to the target, the greater the move's power"),
    PokemonMove("Hail", "Ice", "Status", None, None, 10, "Summons hailstorm for 5 turns"),
    PokemonMove("Hammer Arm", "Fighting", "Physical", 100, 90, 10, "Lowers user's Speed", 100),
    PokemonMove("Happy Hour", "Normal", "Status", None, None, 30, "Doubles the amount of prize money received after battle"),
    PokemonMove("Harden", "Normal", "Status", None, None, 30, "Raises user's Defense"),
    PokemonMove("Haze", "Ice", "Status", None, None, 30, "Resets all stat changes"),
    PokemonMove("Head Charge", "Normal", "Physical", 120, 100, 15, "User receives recoil damage"),
    PokemonMove("Head Smash", "Rock", "Physical", 150, 80, 5, "User receives recoil damage"),
    PokemonMove("Headbutt", "Normal", "Physical", 70, 100, 15, "May cause flinching", 30),
    PokemonMove("Heal Bell", "Normal", "Status", None, None, 5, "Cures all status problems in your party"),
    PokemonMove("Heal Block", "Psychic", "Status", None, 100, 15, "Opponent can't heal for 5 turns"),
    PokemonMove("Heal Order", "Bug", "Status", None, None, 10, "User recovers half of its max HP"),
    PokemonMove("Healing Wish", "Psychic", "Status", None, None, 10, "The user faints, but the next Pokémon released is fully healed"),
    PokemonMove("Heart Stamp", "Psychic", "Physical", 60, 100, 25, "May cause flinching", 30),
    PokemonMove("Heart Swap", "Psychic", "Status", None, None, 10, "User and opponent swap stat changes"),
    PokemonMove("Heat Crash", "Fire", "Physical", None, 100, 10, "The heavier the user compared to the target, the greater the move's power"),
    PokemonMove("Heat Wave", "Fire", "Special", 95, 90, 10, "May burn opponent", 10),
    PokemonMove("Heavy Slam", "Steel", "Physical", None, 100, 10, "The heavier the user compared to the target, the greater the move's power"),
    PokemonMove("Helping Hand", "Normal", "Status", None, None, 20, "Boosts the power of the recipient's move"),
    PokemonMove("Hex", "Ghost", "Special", 65, 100, 10, "Power doubles if opponent is affected by a status condition"),
    PokemonMove("High Horsepower", "Ground", "Physical", 95, 95, 10),
    PokemonMove("High Jump Kick", "Fighting", "Physical", 130, 90, 10, "If it misses, the user loses half its max HP"),
    PokemonMove("Hold Back", "Normal", "Physical", 40, 100, 40, "Always leaves opponent with at least 1 HP"),
    PokemonMove("Hold Hands", "Normal", "Status", None, None, 40, "The user and an ally hold hands. This makes them very happy"),
    PokemonMove("Hone Claws", "Dark", "Status", None, None, 15, "Raises user's Attack and Accuracy"),
    PokemonMove("Horn Attack", "Normal", "Physical", 65, 100, 25),
    PokemonMove("Horn Drill", "Normal", "Physical", None, 30, 5, "One-Hit-KO, if it hits"),
    PokemonMove("Horn Leech", "Grass", "Physical", 75, 100, 10, "User recovers half the HP inflicted on opponent"),
    PokemonMove("Howl", "Normal", "Status", None, None, 40, "Raises user's Attack"),
    PokemonMove("Hurricane", "Flying", "Special", 110, 70, 10, "May confuse opponent", 30),
    PokemonMove("Hydro Cannon", "Water", "Special", 150, 90, 5, "User must recharge next turn"),
    PokemonMove("Hydro Pump", "Water", "Special", 110, 80, 5),
    PokemonMove("Hydro Steam", "Water", "Special", 80, 100, 15, "The move's power is not lowered in harsh sunlight, but rather boosted by 50%"),
    PokemonMove("Hyper Beam", "Normal", "Special", 150, 90, 5, "User must recharge next turn"),
    PokemonMove("Hyper Drill", "Normal", "Physical", 100, 100, 10, "Can hit the target even if it used Protect"),
    PokemonMove("Hyper Fang", "Normal", "Physical", 80, 90, 15, "May cause flinching", 10),
    PokemonMove("Hyper Voice", "Normal", "Special", 90, 100, 10, "Hits all adjacent opponents"),
    PokemonMove("Hyperspace Fury", "Dark", "Physical", 100, None, 5, "Lowers user's Defense. Can't be protected against"),
    PokemonMove("Hyperspace Hole", "Psychic", "Special", 80, None, 5, "Can't be protected against"),
    PokemonMove("Hypnosis", "Psychic", "Status", None, 60, 20, "Puts opponent to sleep"),
    PokemonMove("Ice Ball", "Ice", "Physical", 30, 90, 20, "Doubles in power with each hit"),
    PokemonMove("Ice Beam", "Ice", "Special", 90, 100, 10, "May freeze opponent", 10),
    PokemonMove("Ice Burn", "Ice", "Special", 140, 90, 5, "Charges on first turn, attacks on second. May burn opponent", 30),
    PokemonMove("Ice Fang", "Ice", "Physical", 65, 95, 15, "May cause flinching and/or freeze opponent", 10),
    PokemonMove("Ice Hammer", "Ice", "Physical", 100, 90, 10, "Lowers user's Speed"),
    PokemonMove("Ice Punch", "Ice", "Physical", 75, 100, 15, "May freeze opponent", 10),
    PokemonMove("Ice Shard", "Ice", "Physical", 40, 100, 30, "User attacks first"),
    PokemonMove("Icicle Crash", "Ice", "Physical", 85, 90, 10, "May cause flinching", 30),
    PokemonMove("Icicle Spear", "Ice", "Physical", 25, 100, 30, "Hits 2-5 times in one turn"),
    PokemonMove("Icy Wind", "Ice", "Special", 55, 95, 15, "Lowers opponent's Speed", 100),
    PokemonMove("Imprison", "Psychic", "Status", None, None, 10, "Opponent is prevented from using moves that the user also knows"),
    PokemonMove("Incinerate", "Fire", "Special", 60, 100, 15, "Destroys the opponent's held berry"),
    PokemonMove("Inferno", "Fire", "Special", 100, 50, 5, "Burns opponent", 100),
    PokemonMove("Inferno Overdrive", "Fire", "Physical", None, None, 1, "Fire type Z-Move"),
    PokemonMove("Infernal Parade", "Ghost", "Special", 60, 100, 15, "Power doubles if the target has a status condition"),
    PokemonMove("Ingrain", "Grass", "Status", None, None, 20, "User restores HP each turn, but cannot flee or switch out"),
    PokemonMove("Instruct", "Psychic", "Status", None, None, 15, "Target immediately uses its last move again"),
    PokemonMove("Ion Deluge", "Electric", "Status", None, None, 25, "Normal-type moves become Electric-type for the rest of the turn"),
    PokemonMove("Iron Defense", "Steel", "Status", None, None, 15, "Sharply raises user's Defense"),
    PokemonMove("Iron Head", "Steel", "Physical", 80, 100, 15, "May cause flinching", 30),
    PokemonMove("Iron Tail", "Steel", "Physical", 100, 75, 15, "May lower opponent's Defense", 30),
    PokemonMove("Jaw Lock", "Dark", "Physical", 80, 100, 10, "Prevents user and the target from switching out"),
    PokemonMove("Jet Punch", "Water", "Physical", 60, 100, 15, "User attacks first"),
    PokemonMove("Jungle Healing", "Grass", "Status", None, None, 10, "Restores HP and heals status conditions of user and allies"),
    PokemonMove("Karate Chop", "Fighting", "Physical", 50, 100, 25, "High critical hit ratio"),
    PokemonMove("Kinesis", "Psychic", "Status", None, 80, 15, "Lowers opponent's Accuracy"),
    PokemonMove("King's Shield", "Steel", "Status", None, None, 10, "Protects the user from attacks. Contact moves will lower the attacker's Attack"),
    PokemonMove("Knock Off", "Dark", "Physical", 65, 100, 20, "Removes opponent's held item"),
    PokemonMove("Kowtow Cleave", "Dark", "Physical", 85, None, 10, "The user slashes at the target after kowtowing, boasting that its attack never misses"),
    PokemonMove("Land's Wrath", "Ground", "Physical", 90, 100, 10, "The user gathers the energy of the land and focuses that power on opposing Pokémon to damage them"),
    PokemonMove("Laser Focus", "Normal", "Status", None, None, 30, "The user concentrates intensely. The attack on the next turn always results in a critical hit"),
    PokemonMove("Lash Out", "Dark", "Physical", 75, 100, 5, "Power doubles if user's stats were lowered during the turn"),
    PokemonMove("Last Resort", "Normal", "Physical", 140, 100, 5, "Can only be used after all other moves are used"),
    PokemonMove("Lava Plume", "Fire", "Special", 80, 100, 15, "May burn opponent", 30),
    PokemonMove("Leaf Blade", "Grass", "Physical", 90, 100, 15, "High critical hit ratio"),
    PokemonMove("Leaf Storm", "Grass", "Special", 130, 90, 5, "Sharply lowers user's Special Attack", 100),
    PokemonMove("Leaf Tornado", "Grass", "Special", 65, 90, 10, "May lower opponent's Accuracy", 50),
    PokemonMove("Leafage", "Grass", "Physical", 40, 100, 40),
    PokemonMove("Leech Life", "Bug", "Physical", 80, 100, 10, "User recovers half the HP inflicted on opponent"),
    PokemonMove("Leech Seed", "Grass", "Status", None, 90, 10, "Steals HP from opponent every turn"),
    PokemonMove("Leer", "Normal", "Status", None, 100, 30, "Lowers opponent's Defense"),
    PokemonMove("Let’s Snuggle Forever", "Fairy", "Physical", 190, None, 1, "Mimikyu-exclusive Z-Move"),
    PokemonMove("Lick", "Ghost", "Physical", 30, 100, 30, "May paralyze opponent", 30),
    PokemonMove("Life Dew", "Water", "Status", None, None, 10, "The user scatters mysterious water around and restores the HP of itself and its ally Pokémon in the battle"),
    PokemonMove("Light of Ruin", "Fairy", "Special", 140, 90, 5, "User receives recoil damage"),
    PokemonMove("Light Screen", "Psychic", "Status", None, None, 30, "Halves damage from Special attacks for 5 turns"),
    PokemonMove("Light That Burns the Sky", "Psychic", "Special", 200, None, 1, "Necrozma's exclusive Z-Move. Power decreases if used by Pokémon other than Necrozma"),
    PokemonMove("Liquidation", "Water", "Physical", 85, 100, 10, "May lower opponent's Defense", 20),
    PokemonMove("Lock-On", "Normal", "Status", None, None, 5, "User's next move will not miss"),
    PokemonMove("Lovely Kiss", "Normal", "Status", None, 75, 10, "Puts opponent to sleep"),
    PokemonMove("Low Kick", "Fighting", "Physical", None, 100, 20, "The heavier the opponent, the stronger the attack"),
    PokemonMove("Low Sweep", "Fighting", "Physical", 65, 100, 20, "Lowers opponent's Speed", 100),
    PokemonMove("Lucky Chant", "Normal", "Status", None, None, 30, "Opponent cannot land critical hits for 5 turns"),
    PokemonMove("Lunar Blessing", "Psychic", "Status", None, None, 10, "User heals its own status conditions and restores HP to itself and its allies. Raises evasiveness"),
    PokemonMove("Lunar Dance", "Psychic", "Status", None, None, 10, "User faints, and the next Pokémon released is fully healed"),
    PokemonMove("Lunge", "Bug", "Physical", 80, 100, 15, "Lowers opponent's Attack"),
    PokemonMove("Luster Purge", "Psychic", "Special", 70, 100, 5, "May lower opponent's Special Defense", 50),
    PokemonMove("Mach Punch", "Fighting", "Physical", 40, 100, 30, "User attacks first"),
    PokemonMove("Magical Leaf", "Grass", "Special", 60, None, 20, "Ignores Accuracy and Evasiveness"),
    PokemonMove("Magic Coat", "Psychic", "Status", None, None, 15, "Reflects status moves back to the opponent"),
    PokemonMove("Magic Powder", "Psychic", "Status", None, 100, 20, "Changes the target into Psychic-type"),
    PokemonMove("Magic Room", "Psychic", "Status", None, None, 10, "Suppresses the effects of held items for 5 turns"),
    PokemonMove("Magma Storm", "Fire", "Special", 100, 75, 5, "Traps opponent, damaging them for 4-5 turns"),
    PokemonMove("Magnet Bomb", "Steel", "Physical", 60, None, 20, "Ignores Accuracy and Evasiveness"),
    PokemonMove("Magnet Rise", "Electric", "Status", None, None, 10, "The user levitates with electromagnetism for five turns"),
    PokemonMove("Magnetic Flux", "Electric", "Status", None, None, 20, "Boosts Defense and Special Defense of allies with Plus or Minus Ability"),
    PokemonMove("Magnitude", "Ground", "Physical", None, 100, 30, "Hits with random power"),
    PokemonMove("Make It Rain", "Steel", "Special", 120, 100, 5, "User attacks by throwing out a mass of coins. Lowers user's Special Attack"),
    PokemonMove("Malicious Moonsault", "Dark", "Physical", 180, None, 1, "Incineroar-exclusive Z-Move"),
    PokemonMove("Mat Block", "Fighting", "Status", None, None, 10, "Protects user's team from damaging moves"),
    PokemonMove("Max Airstream", "Flying", "Physical", None, None, 10, "Flying-type Dynamax move. Boosts Speed of user and allies"),
    PokemonMove("Max Darkness", "Dark", "Physical", None, None, 10, "Dark-type Dynamax move. Lowers Special Defense of opponents"),
    PokemonMove("Max Flare", "Fire", "Physical", None, None, 10, "Fire-type Dynamax move. Sets up sunlight"),
    PokemonMove("Max Flutterby", "Bug", "Physical", None, None, 10, "Bug-type Dynamax move. Lowers Special Attack of opponents"),
    PokemonMove("Max Geyser", "Water", "Physical", None, None, 10, "Water-type Dynamax move. Sets up rain"),
    PokemonMove("Max Guard", "Normal", "Status", None, None, 10, "Normal-type Dynamax move. Protects the user from attacks"),
    PokemonMove("Max Hailstorm", "Ice", "Physical", None, None, 10, "Ice-type Dynamax move. Sets up hailstorm"),
    PokemonMove("Max Knuckle", "Fighting", "Physical", None, None, 10, "Fighting-type Dynamax move. Boosts Attack of user and allies"),
    PokemonMove("Max Lightning", "Electric", "Physical", None, None, 10, "Electric-type Dynamax move. Sets up Electric Terrain"),
    PokemonMove("Max Mindstorm", "Psychic", "Physical", None, None, 10, "Psychic-type Dynamax move. Sets up Psychic Terrain"),
    PokemonMove("Max Ooze", "Poison", "Physical", None, None, 10, "Poison-type Dynamax move. Boosts Special Attack of user and allies"),
    PokemonMove("Max Overgrowth", "Grass", "Physical", None, None, 10, "Grass-type Dynamax move. Sets up Grassy Terrain"),
    PokemonMove("Max Phantasm", "Ghost", "Physical", None, None, 10, "Ghost-type Dynamax move. Lowers Defense of opponents"),
    PokemonMove("Max Quake", "Ground", "Physical", None, None, 10, "Ground-type Dynamax move. Boosts Special Defense of user and allies"),
    PokemonMove("Max Rockfall", "Rock", "Physical", None, None, 10, "Rock-type Dynamax move. Sets up sandstorm"),
    PokemonMove("Max Starfall", "Fairy", "Physical", None, None, 10, "Fairy-type Dynamax move. Sets up Misty Terrain"),
    PokemonMove("Max Steelspike", "Steel", "Physical", None, None, 10, "Steel-type Dynamax move. Boosts Defense of user and allies"),
    PokemonMove("Max Strike", "Normal", "Physical", None, None, 10, "Normal-type Dynamax move. Lowers Speed of opponents"),
    PokemonMove("Max Wyrmwind", "Dragon", "Physical", None, None, 10, "Dragon-type Dynamax move. Lowers Attack of opponents"),
    PokemonMove("Mean Look", "Normal", "Status", None, None, 5, "Opponent cannot flee or switch"),
    PokemonMove("Meditate", "Psychic", "Status", None, None, 40, "Raises user's Attack"),
    PokemonMove("Mega Drain", "Grass", "Special", 40, 100, 15, "User recovers half the HP inflicted on opponent"),
    PokemonMove("Mega Kick", "Normal", "Physical", 120, 75, 5),
    PokemonMove("Mega Punch", "Normal", "Physical", 80, 85, 20),
    PokemonMove("Megahorn", "Bug", "Physical", 120, 85, 10),
    PokemonMove("Memento", "Dark", "Status", None, 100, 10, "User faints, opponent's Attack and Special Attack are cut sharply"),
    PokemonMove("Menacing Moonraze Maelstrom", "Ghost", "Special", 200, None, 1, "Lunala-exclusive Z-Move"),
    PokemonMove("Metal Burst", "Steel", "Physical", None, 100, 10, "Retaliates with greater power against the last move"),
    PokemonMove("Metal Claw", "Steel", "Physical", 50, 95, 35, "May raise user's Attack", 10),
    PokemonMove("Metal Sound", "Steel", "Status", None, 85, 40, "Sharply lowers opponent's Special Defense"),
    PokemonMove("Meteor Assault", "Fighting", "Physical", 150, 100, 5, "User must recharge next turn"),
    PokemonMove("Meteor Beam", "Rock", "Special", 120, 90, 10, "Charges on first turn, attacks on second. Raises user's Special Attack"),
    PokemonMove("Meteor Mash", "Steel", "Physical", 90, 90, 10, "May raise user's Attack", 20),
    PokemonMove("Metronome", "Normal", "Status", None, None, 10, "User performs nearly any move in the game at random"),
    PokemonMove("Milk Drink", "Normal", "Status", None, None, 10, "User recovers half its max HP"),
    PokemonMove("Mimic", "Normal", "Status", None, None, 10, "Copies the opponent's last move"),
    PokemonMove("Mind Blown", "Fire", "Special", 150, 100, 5, "User loses 50% of its max HP."),
    PokemonMove("Mind Reader", "Normal", "Status", None, None, 5, "Ensures the next attack will hit."),
    PokemonMove("Minimize", "Normal", "Status", None, None, 10, "Sharply raises user's Evasiveness."),
    PokemonMove("Miracle Eye", "Psychic", "Status", None, None, 40, "Resets opponent's Evasiveness, removes Dark's Psychic immunity."),
    PokemonMove("Mirror Coat", "Psychic", "Special", None, 100, 20, "When hit by a Special Attack, user strikes back with 2x power."),
    PokemonMove("Mirror Move", "Flying", "Status", None, None, 20, "User performs the opponent's last move."),
    PokemonMove("Mirror Shot", "Steel", "Special", 65, 85, 10, "May lower opponent's Accuracy."),
    PokemonMove("Mist", "Ice", "Status", None, None, 30, "User's stats cannot be changed for a period of time."),
    PokemonMove("Mist Ball", "Psychic", "Special", 70, 100, 5, "May lower opponent's Special Attack."),
    PokemonMove("Misty Explosion", "Fairy", "Special", 100, 100, 5, "Power increases on Misty Terrain."),
    PokemonMove("Misty Terrain", "Fairy", "Status", None, None, 10, "Protects the field from status conditions for 5 turns."),
    PokemonMove("Moonblast", "Fairy", "Special", 95, 100, 15, "May lower opponent's Special Attack."),
    PokemonMove("Moongeist Beam", "Ghost", "Special", 100, 100, 5, "Ignores the opponent's ability."),
    PokemonMove("Moonlight", "Fairy", "Status", None, None, 5, "Restores HP based on the weather."),
    PokemonMove("Morning Sun", "Normal", "Status", None, None, 5, "Restores HP based on the weather."),
    PokemonMove("Mud Bomb", "Ground", "Special", 65, 85, 10, "May lower opponent's Accuracy."),
    PokemonMove("Mud Shot", "Ground", "Special", 55, 95, 15, "Lowers opponent's Speed."),
    PokemonMove("Mud Sport", "Ground", "Status", None, None, 15, "Weakens the power of Electric-type moves."),
    PokemonMove("Mud-Slap", "Ground", "Special", 20, 100, 10, "Lowers opponent's Accuracy."),
    PokemonMove("Muddy Water", "Water", "Special", 90, 85, 10, "May lower opponent's Accuracy."),
    PokemonMove("Multi-Attack", "Normal", "Physical", 120, 100, 10, "Type varies with the held item."),
    PokemonMove("Mystical Fire", "Fire", "Special", 75, 100, 10, "Lowers opponent's Special Attack."),
    PokemonMove("Nasty Plot", "Dark", "Status", None, None, 20, "Sharply raises user's Special Attack."),
    PokemonMove("Natural Gift", "Normal", "Physical", None, 100, 15, "Type and power depend on the held Berry."),
    PokemonMove("Nature Power", "Normal", "Status", None, None, 20, "Uses a move depending on the terrain."),
    PokemonMove("Nature's Madness", "Fairy", "Special", None, 90, 10, "Halves the opponent's HP."),
    PokemonMove("Needle Arm", "Grass", "Physical", 60, 100, 15, "May cause flinching."),
    PokemonMove("Night Daze", "Dark", "Special", 85, 95, 10, "May lower opponent's Accuracy."),
    PokemonMove("Night Shade", "Ghost", "Special", None, 100, 15, "Deals damage equal to user's level."),
    PokemonMove("Night Slash", "Dark", "Physical", 70, 100, 15, "High critical hit ratio."),
    PokemonMove("Noble Roar", "Normal", "Status", None, 100, 30, "Lowers opponent's Attack and Special Attack."),
    PokemonMove("Noxious Torque", "Poison", "Physical", 100, 100, 5, "May poison opponent."),
    PokemonMove("Oblivion Wing", "Flying", "Special", 80, 100, 10, "User recovers HP equal to damage dealt."),
    PokemonMove("Oceanic Operetta", "Water", "Special", 195, 100, 1, "Primarina-exclusive Z-Move."),
    PokemonMove("Octazooka", "Water", "Special", 65, 85, 10, "May lower opponent's Accuracy."),
    PokemonMove("Octolock", "Fighting", "Status", None, None, 15, "Prevents opponent from escaping and lowers Defense and Special Defense."),
    PokemonMove("Odor Sleuth", "Normal", "Status", None, None, 40, "Enables Normal and Fighting moves to hit Ghost-type Pokémon."),
    PokemonMove("Ominous Wind", "Ghost", "Special", 60, 100, 5, "May raise all of user's stats."),
    PokemonMove("Origin Pulse", "Water", "Special", 110, 85, 10, "Hits all adjacent opponents."),
    PokemonMove("Outrage", "Dragon", "Physical", 120, 100, 10, "User attacks for 2-3 turns but then becomes confused."),
    PokemonMove("Overdrive", "Electric", "Special", 80, 100, 10, "Hits all adjacent opponents."),
    PokemonMove("Overheat", "Fire", "Special", 130, 90, 5, "Sharply lowers user's Special Attack."),
    PokemonMove("Pain Split", "Normal", "Status", None, None, 20, "The user's and opponent's HP become the average of both."),
    PokemonMove("Parabolic Charge", "Electric", "Special", 65, 100, 20, "User recovers half the HP inflicted on opponent."),
    PokemonMove("Parting Shot", "Dark", "Status", None, 100, 20, "Lowers opponent's Attack and Special Attack then switches out."),
    PokemonMove("Pay Day", "Normal", "Physical", 40, 100, 20, "Money is earned after the battle."),
    PokemonMove("Payback", "Dark", "Physical", 50, 100, 10, "Power doubles if the user was attacked first."),
    PokemonMove("Peck", "Flying", "Physical", 35, 100, 35, None),
    PokemonMove("Perish Song", "Normal", "Status", None, None, 5, "Any Pokémon in play when this attack is used faints in 3 turns."),
    PokemonMove("Petal Blizzard", "Grass", "Physical", 90, 100, 15, "Hits all adjacent Pokémon."),
    PokemonMove("Petal Dance", "Grass", "Special", 120, 100, 10, "User attacks for 2-3 turns but then becomes confused."),
    PokemonMove("Phantom Force", "Ghost", "Physical", 90, 100, 10, "Disappears on first turn, strikes on second. Can hit through Protect/Detect."),
    PokemonMove("Photon Geyser", "Psychic", "Special", 100, 100, 5, "Calculates damage based on user's higher Attack or Special Attack."),
    PokemonMove("Pika Papow", "Electric", "Special", None, 100, 20, "Power increases with the player's bond."),
    PokemonMove("Pin Missile", "Bug", "Physical", 25, 95, 20, "Hits 2-5 times in one turn."),
    PokemonMove("Plasma Fists", "Electric", "Physical", 100, 100, 15, "Normal-type moves become Electric-type during the turn."),
    PokemonMove("Play Nice", "Normal", "Status", None, None, 20, "Lowers opponent's Attack without fail."),
    PokemonMove("Play Rough", "Fairy", "Physical", 90, 90, 10, "May lower opponent's Attack."),
    PokemonMove("Pluck", "Flying", "Physical", 60, 100, 20, "If opponent is holding a berry, its effect is stolen by user."),
    PokemonMove("Poison Fang", "Poison", "Physical", 50, 100, 15, "May badly poison opponent."),
    PokemonMove("Poison Gas", "Poison", "Status", None, 90, 40, "Poisons opponent."),
    PokemonMove("Poison Jab", "Poison", "Physical", 80, 100, 20, "May poison opponent."),
    PokemonMove("Poison Powder", "Poison", "Status", None, 75, 35, "Poisons opponent."),
    PokemonMove("Poison Sting", "Poison", "Physical", 15, 100, 35, "May poison opponent."),
    PokemonMove("Poison Tail", "Poison", "Physical", 50, 100, 25, "High critical hit ratio. May poison opponent."),
    PokemonMove("Pollen Puff", "Bug", "Special", 90, 100, 15, "If used on an ally, restores HP instead of dealing damage."),
    PokemonMove("Poltergeist", "Ghost", "Physical", 110, 90, 5, "Fails if opponent has no held item."),
    PokemonMove("Population Bomb", "Normal", "Physical", 20, 90, 10, "Hits 1-10 times in one turn."),
    PokemonMove("Pounce", "Bug", "Physical", 50, 100, 20, "Lowers opponent's Speed."),
    PokemonMove("Powder", "Bug", "Status", None, 100, 20, "Damages target if it uses a Fire-type move."),
    PokemonMove("Powder Snow", "Ice", "Special", 40, 100, 25, "May freeze opponent."),
    PokemonMove("Power Gem", "Rock", "Special", 80, 100, 20, None),
    PokemonMove("Power Split", "Psychic", "Status", None, None, 10, "Averages Attack and Special Attack with the target."),
    PokemonMove("Power Swap", "Psychic", "Status", None, None, 10, "Swaps Attack and Special Attack with the target."),
    PokemonMove("Power Trick", "Psychic", "Status", None, None, 10, "Swaps user's Attack and Defense stats."),
    PokemonMove("Power Trip", "Dark", "Physical", 20, 100, 10, "Power increases when user's stats are raised."),
    PokemonMove("Power Whip", "Grass", "Physical", 120, 85, 10, None),
    PokemonMove("Power-Up Punch", "Fighting", "Physical", 40, 100, 20, "Raises user's Attack."),
    PokemonMove("Precipice Blades", "Ground", "Physical", 120, 85, 10, "Hits all adjacent opponents."),
    PokemonMove("Present", "Normal", "Physical", None, 90, 15, "Either deals damage or heals."),
    PokemonMove("Prismatic Laser", "Psychic", "Special", 160, 100, 10, "User can't move on the next turn."),
    PokemonMove("Protect", "Normal", "Status", None, None, 10, "Protects the user, but may fail if used consecutively."),
    PokemonMove("Psybeam", "Psychic", "Special", 65, 100, 20, "May confuse opponent."),
    PokemonMove("Psyblade", "Psychic", "Physical", 80, 100, 15, "Power increases on Electric Terrain."),
    PokemonMove("Psych Up", "Normal", "Status", None, None, 10, "Copies the opponent's stat changes."),
    PokemonMove("Psychic", "Psychic", "Special", 90, 100, 10, "May lower opponent's Special Defense."),
    PokemonMove("Psychic Fangs", "Psychic", "Physical", 85, 100, 10, "Destroys Light Screen and Reflect."),
    PokemonMove("Psychic Noise", "Psychic", "Special", 75, 100, 10, "Prevents opponent from healing."),
    PokemonMove("Psychic Terrain", "Psychic", "Status", None, None, 10, "Prevents priority moves for 5 turns."),
    PokemonMove("Psycho Boost", "Psychic", "Special", 140, 90, 5, "Sharply lowers user's Special Attack."),
    PokemonMove("Psycho Cut", "Psychic", "Physical", 70, 100, 20, "High critical hit ratio."),
    PokemonMove("Psycho Shift", "Psychic", "Status", None, 100, 10, "Transfers user's status condition to opponent."),
    PokemonMove("Psyshield Bash", "Psychic", "Physical", 70, 90, 10, "Raises user's Defense and Special Defense."),
    PokemonMove("Psyshock", "Psychic", "Special", 80, 100, 10, "Inflicts damage based on target's Defense."),
    PokemonMove("Psystrike", "Psychic", "Special", 100, 100, 10, "Inflicts damage based on target's Defense."),
    PokemonMove("Psywave", "Psychic", "Special", None, 100, 15, "Inflicts damage 50-150% of user's level."),
    PokemonMove("Pulverizing Pancake", "Normal", "Physical", 210, None, 1, "Snorlax-exclusive Normal-type Z-Move."),
    PokemonMove("Punishment", "Dark", "Physical", None, 100, 5, "Power increases when opponent's stats are raised."),
    PokemonMove("Purify", "Poison", "Status", None, None, 20, "Heals target's status condition and restores user's HP."),
    PokemonMove("Pursuit", "Dark", "Physical", 40, 100, 20, "Double power if opponent is switching out."),
    PokemonMove("Pyro Ball", "Fire", "Physical", 120, 90, 5, "May burn opponent."),
    PokemonMove("Quash", "Dark", "Status", None, 100, 15, "Makes the target act last this turn."),
    PokemonMove("Quick Attack", "Normal", "Physical", 40, 100, 30, "User attacks first."),
    PokemonMove("Quick Guard", "Fighting", "Status", None, None, 15, "Protects the user's team from high-priority moves."),
    PokemonMove("Rage", "Normal", "Physical", 20, 100, 20, "Increases Attack each time the user is hit."),
    PokemonMove("Rage Powder", "Bug", "Status", None, None, 20, "Forces attacks to hit the user instead of its allies."),
    PokemonMove("Rain Dance", "Water", "Status", None, None, 5, "Makes it rain for 5 turns."),
    PokemonMove("Rapid Spin", "Normal", "Physical", 50, 100, 40, "Frees user from bind, wrap, leech seed, and spikes."),
    PokemonMove("Razor Leaf", "Grass", "Physical", 55, 95, 25, "High critical hit ratio."),
    PokemonMove("Razor Shell", "Water", "Physical", 75, 95, 10, "May lower opponent's Defense."),
    PokemonMove("Recover", "Normal", "Status", None, None, 10, "Restores half the user's max HP."),
    PokemonMove("Reflect", "Psychic", "Status", None, None, 20, "Halves damage from Physical attacks for 5 turns."),
    PokemonMove("Rest", "Psychic", "Status", None, None, 10, "User sleeps for 2 turns and restores HP."),
    PokemonMove("Retaliate", "Normal", "Physical", 70, 100, 5, "Power doubles if an ally fainted last turn."),
    PokemonMove("Revenge", "Fighting", "Physical", 60, 100, 10, "Power doubles if user was hit first."),
    PokemonMove("Reversal", "Fighting", "Physical", None, 100, 15, "Power increases as user's HP decreases."),
    PokemonMove("Roar", "Normal", "Status", None, None, 20, "Forces opponent to switch Pokémon."),
    PokemonMove("Rock Blast", "Rock", "Physical", 25, 90, 10, "Hits 2-5 times in one turn."),
    PokemonMove("Rock Polish", "Rock", "Status", None, None, 20, "Sharply raises user's Speed."),
    PokemonMove("Rock Slide", "Rock", "Physical", 75, 90, 10, "May cause flinching."),
    PokemonMove("Rock Smash", "Fighting", "Physical", 40, 100, 15, "May lower opponent's Defense."),
    PokemonMove("Rock Throw", "Rock", "Physical", 50, 90, 15, None),
    PokemonMove("Rock Tomb", "Rock", "Physical", 60, 95, 15, "Lowers opponent's Speed."),
    PokemonMove("Rock Wrecker", "Rock", "Physical", 150, 90, 5, "User can't move on the next turn."),
    PokemonMove("Role Play", "Psychic", "Status", None, None, 10, "Copies the opponent's ability."),
    PokemonMove("Rolling Kick", "Fighting", "Physical", 60, 85, 15, "May cause flinching."),
    PokemonMove("Rollout", "Rock", "Physical", 30, 90, 20, "Power doubles with each hit."),
    PokemonMove("Roost", "Flying", "Status", None, None, 10, "User restores HP and loses Flying type for the turn."),
    PokemonMove("Round", "Normal", "Special", 60, 100, 15, "Power increases if teammates use it consecutively."),
    PokemonMove("Sacred Fire", "Fire", "Physical", 100, 95, 5, "May burn opponent."),
    PokemonMove("Sacred Sword", "Fighting", "Physical", 90, 100, 15, "Ignores opponent's stat changes."),
    PokemonMove("Safeguard", "Normal", "Status", None, None, 25, "Prevents the user's team from status conditions for 5 turns."),
    PokemonMove("Sand Attack", "Ground", "Status", None, 100, 15, "Lowers opponent's Accuracy."),
    PokemonMove("Sand Tomb", "Ground", "Physical", 35, 85, 15, "Traps opponent, damaging it for 4-5 turns."),
    PokemonMove("Sandstorm", "Rock", "Status", None, None, 10, "Raises the Special Defense of Rock types for 5 turns."),
    PokemonMove("Scald", "Water", "Special", 80, 100, 15, "May burn opponent."),
    PokemonMove("Scale Shot", "Dragon", "Physical", 25, 90, 20, "Hits 2-5 times, raises Speed and lowers Defense."),
    PokemonMove("Scary Face", "Normal", "Status", None, 100, 10, "Sharply lowers opponent's Speed."),
    PokemonMove("Scratch", "Normal", "Physical", 40, 100, 35, None),
    PokemonMove("Screech", "Normal", "Status", None, 85, 40, "Sharply lowers opponent's Defense."),
    PokemonMove("Searing Shot", "Fire", "Special", 100, 100, 5, "May burn opponent."),
    PokemonMove("Secret Power", "Normal", "Physical", 70, 100, 20, "Effects vary with terrain."),
    PokemonMove("Secret Sword", "Fighting", "Special", 85, 100, 10, "Inflicts damage based on the target's Defense."),
    PokemonMove("Seed Bomb", "Grass", "Physical", 80, 100, 15, None),
    PokemonMove("Seed Flare", "Grass", "Special", 120, 85, 5, "May sharply lower opponent's Special Defense."),
    PokemonMove("Seismic Toss", "Fighting", "Physical", None, 100, 20, "Inflicts damage equal to user's level."),
    PokemonMove("Self-Destruct", "Normal", "Physical", 200, 100, 5, "User faints."),
    PokemonMove("Shadow Ball", "Ghost", "Special", 80, 100, 15, "May lower opponent's Special Defense."),
    PokemonMove("Shadow Bone", "Ghost", "Physical", 85, 100, 10, "May lower opponent's Defense."),
    PokemonMove("Shadow Claw", "Ghost", "Physical", 70, 100, 15, "High critical hit ratio."),
    PokemonMove("Shadow Force", "Ghost", "Physical", 120, 100, 5, "Disappears on first turn, strikes on second."),
    PokemonMove("Shadow Punch", "Ghost", "Physical", 60, None, 20, "Never misses."),
    PokemonMove("Shadow Sneak", "Ghost", "Physical", 40, 100, 30, "User attacks first."),
    PokemonMove("Sharpen", "Normal", "Status", None, None, 30, "Raises user's Attack."),
    PokemonMove("Sheer Cold", "Ice", "Special", None, 30, 5, "One-Hit-KO move."),
    PokemonMove("Shell Side Arm", "Poison", "Special", 90, 100, 10, "Deals Physical or Special damage, whichever is better."),
    PokemonMove("Shell Smash", "Normal", "Status", None, None, 15, "Sharply raises user's Attack, Special Attack, and Speed."),
    PokemonMove("Shift Gear", "Steel", "Status", None, None, 10, "Raises user's Attack and sharply raises Speed."),
    PokemonMove("Shock Wave", "Electric", "Special", 60, None, 20, "Never misses."),
    PokemonMove("Shore Up", "Ground", "Status", None, None, 10, "Restores user's HP; more in a sandstorm."),
    PokemonMove("Signal Beam", "Bug", "Special", 75, 100, 15, "May confuse opponent."),
    PokemonMove("Silver Wind", "Bug", "Special", 60, 100, 5, "May raise all user's stats."),
    PokemonMove("Simple Beam", "Normal", "Status", None, 100, 15, "Changes the opponent's Ability to Simple."),
    PokemonMove("Sing", "Normal", "Status", None, 55, 15, "Puts opponent to sleep."),
    PokemonMove("Skull Bash", "Normal", "Physical", 130, 100, 10, "Raises Defense on the first turn, attacks on the second."),
    PokemonMove("Sky Attack", "Flying", "Physical", 140, 90, 5, "Charges on first turn, attacks on second. May cause flinching."),
    PokemonMove("Sky Drop", "Flying", "Physical", 60, 100, 10, "Takes opponent into the air on first turn, drops them on the second."),
    PokemonMove("Sky Uppercut", "Fighting", "Physical", 85, 90, 15, "Can hit opponents using Fly."),
    PokemonMove("Slack Off", "Normal", "Status", None, None, 10, "Restores half of the user's max HP."),
    PokemonMove("Slam", "Normal", "Physical", 80, 75, 20, None),
    PokemonMove("Slash", "Normal", "Physical", 70, 100, 20, "High critical hit ratio."),
    PokemonMove("Sleep Powder", "Grass", "Status", None, 75, 15, "Puts opponent to sleep."),
    PokemonMove("Sleep Talk", "Normal", "Status", None, None, 10, "Uses one of the user's moves while asleep."),
    PokemonMove("Sludge", "Poison", "Special", 65, 100, 20, "May poison opponent."),
    PokemonMove("Sludge Bomb", "Poison", "Special", 90, 100, 10, "May poison opponent."),
    PokemonMove("Sludge Wave", "Poison", "Special", 95, 100, 10, "May poison opponent."),
    PokemonMove("Smack Down", "Rock", "Physical", 50, 100, 15, "Makes Flying-type opponents susceptible to Ground moves."),
    PokemonMove("Smelling Salts", "Normal", "Physical", 70, 100, 10, "Doubles power if opponent is paralyzed but cures it."),
    PokemonMove("Smog", "Poison", "Special", 30, 70, 20, "May poison opponent."),
    PokemonMove("Smokescreen", "Normal", "Status", None, 100, 20, "Lowers opponent's Accuracy."),
    PokemonMove("Snap Trap", "Grass", "Physical", 35, 100, 15, "Traps opponent, damaging it for 4-5 turns."),
    PokemonMove("Snarl", "Dark", "Special", 55, 95, 15, "Lowers opponent's Special Attack."),
    PokemonMove("Snatch", "Dark", "Status", None, None, 10, "Steals the effects of the opponent's healing or status moves."),
    PokemonMove("Snore", "Normal", "Special", 50, 100, 15, "Can only be used if the user is asleep. May cause flinching."),
    PokemonMove("Soak", "Water", "Status", None, 100, 20, "Changes opponent's type to Water."),
    PokemonMove("Soft-Boiled", "Normal", "Status", None, None, 10, "User restores half of its max HP."),
    PokemonMove("Solar Beam", "Grass", "Special", 120, 100, 10, "Charges on first turn, attacks on second."),
    PokemonMove("Solar Blade", "Grass", "Physical", 125, 100, 10, "Charges on first turn, attacks on second."),
    PokemonMove("Spark", "Electric", "Physical", 65, 100, 20, "May paralyze opponent."),
    PokemonMove("Sparkling Aria", "Water", "Special", 90, 100, 10, "Heals the burns of the target."),
    PokemonMove("Spectral Thief", "Ghost", "Physical", 90, 100, 10, "Steals opponent's stat boosts before attacking."),
    PokemonMove("Speed Swap", "Psychic", "Status", None, None, 10, "Swaps Speed stats with opponent."),
    PokemonMove("Spicy Extract", "Grass", "Status", None, None, 15, "Sharply raises target's Attack and lowers Defense."),
    PokemonMove("Spider Web", "Bug", "Status", None, None, 10, "Prevents opponent from escaping."),
    PokemonMove("Spike Cannon", "Normal", "Physical", 20, 100, 15, "Hits 2-5 times in one turn."),
    PokemonMove("Spikes", "Ground", "Status", None, None, 20, "Damages opponents switching into battle."),
    PokemonMove("Spiky Shield", "Grass", "Status", None, None, 10, "Protects user and damages opponent on contact."),
    PokemonMove("Spirit Break", "Fairy", "Physical", 75, 100, 15, "Lowers opponent's Special Attack."),
    PokemonMove("Spirit Shackle", "Ghost", "Physical", 80, 100, 10, "Prevents opponent from escaping."),
    PokemonMove("Spit Up", "Normal", "Special", None, 100, 10, "Power depends on how many times the user used Stockpile."),
    PokemonMove("Spite", "Ghost", "Status", None, 100, 10, "Lowers opponent's PP by 4."),
    PokemonMove("Splash", "Normal", "Status", None, None, 40, "Does nothing."),
    PokemonMove("Spore", "Grass", "Status", None, 100, 15, "Puts opponent to sleep."),
    PokemonMove("Springtide Storm", "Fairy", "Special", 100, 80, 5, "May lower opponent's Attack."),
    PokemonMove("Stakataka", "Rock", "Physical", 100, 100, 5, "May raise user's Defense."),
    PokemonMove("Stalwart", "Steel", "Special", 90, 100, 10, "Ignores opponent's ability."),
    PokemonMove("Stance Change", "Ghost", "Status", None, None, 5, "Changes form to Blade or Shield."),
    PokemonMove("Steam Eruption", "Water", "Special", 110, 95, 5, "May burn opponent."),
    PokemonMove("Steamroller", "Bug", "Physical", 65, 100, 20, "May cause flinching."),
    PokemonMove("Steel Beam", "Steel", "Special", 140, 95, 5, "User loses 50% of its max HP."),
    PokemonMove("Steel Roller", "Steel", "Physical", 130, 100, 5, "Removes terrain."),
    PokemonMove("Steel Wing", "Steel", "Physical", 70, 90, 25, "May raise user's Defense."),
    PokemonMove("Sticky Web", "Bug", "Status", None, None, 20, "Lowers Speed of opponents switching into battle."),
    PokemonMove("Stockpile", "Normal", "Status", None, None, 20, "Stores energy for use with Spit Up or Swallow."),
    PokemonMove("Stomp", "Normal", "Physical", 65, 100, 20, "May cause flinching."),
    PokemonMove("Stomping Tantrum", "Ground", "Physical", 75, 100, 10, "Power doubles if previous move failed."),
    PokemonMove("Stone Edge", "Rock", "Physical", 100, 80, 5, "High critical hit ratio."),
    PokemonMove("Stored Power", "Psychic", "Special", 20, 100, 10, "Power increases when user's stats are raised."),
    PokemonMove("Storm Throw", "Fighting", "Physical", 60, 100, 10, "Always results in a critical hit."),
    PokemonMove("Strange Steam", "Fairy", "Special", 90, 95, 10, "May confuse opponent."),
    PokemonMove("Strength", "Normal", "Physical", 80, 100, 15, None),
    PokemonMove("Strength Sap", "Grass", "Status", None, 100, 10, "Restores HP by the amount equal to the opponent's Attack."),
    PokemonMove("String Shot", "Bug", "Status", None, 95, 40, "Sharply lowers opponent's Speed."),
    PokemonMove("Struggle", "Normal", "Physical", 50, None, None, "Only usable when all PP are gone. Hurts the user."),
    PokemonMove("Struggle Bug", "Bug", "Special", 50, 100, 20, "Lowers opponent's Special Attack."),
    PokemonMove("Stuff Cheeks", "Normal", "Status", None, None, 10, "Eats the user's Berry and sharply raises Defense."),
    PokemonMove("Stun Spore", "Grass", "Status", None, 75, 30, "Paralyzes opponent."),
    PokemonMove("Submission", "Fighting", "Physical", 80, 80, 20, "User receives recoil damage."),
    PokemonMove("Substitute", "Normal", "Status", None, None, 10, "Uses HP to create a decoy that takes hits."),
    PokemonMove("Sucker Punch", "Dark", "Physical", 70, 100, 5, "User attacks first, but only if opponent is readying an attack."),
    PokemonMove("Sunny Day", "Fire", "Status", None, None, 5, "Makes it sunny for 5 turns."),
    PokemonMove("Sunsteel Strike", "Steel", "Physical", 100, 100, 5, "Ignores the target's ability."),
    PokemonMove("Super Fang", "Normal", "Physical", None, 90, 10, "Always reduces the opponent's HP by half."),
    PokemonMove("Superpower", "Fighting", "Physical", 120, 100, 5, "Lowers user's Attack and Defense."),
    PokemonMove("Supersonic", "Normal", "Status", None, 55, 20, "Confuses opponent."),
    PokemonMove("Surf", "Water", "Special", 90, 100, 15, "Hits all adjacent Pokémon."),
    PokemonMove("Swagger", "Normal", "Status", None, 85, 15, "Sharply raises opponent's Attack but confuses it."),
    PokemonMove("Swallow", "Normal", "Status", None, None, 10, "Heals based on Stockpile count."),
    PokemonMove("Sweet Kiss", "Fairy", "Status", None, 75, 10, "Confuses opponent."),
    PokemonMove("Sweet Scent", "Normal", "Status", None, 100, 20, "Lowers opponent's Evasiveness."),
    PokemonMove("Swift", "Normal", "Special", 60, None, 20, "Never misses."),
    PokemonMove("Swords Dance", "Normal", "Status", None, None, 20, "Sharply raises user's Attack."),
    PokemonMove("Synchronoise", "Psychic", "Special", 120, 100, 15, "Hits opponents sharing the user's type."),
    PokemonMove("Synthesis", "Grass", "Status", None, None, 5, "Restores HP based on the weather."),
    PokemonMove("Tackle", "Normal", "Physical", 40, 100, 35, None),
    PokemonMove("Tail Glow", "Bug", "Status", None, None, 20, "Sharply raises user's Special Attack."),
    PokemonMove("Tail Slap", "Normal", "Physical", 25, 85, 10, "Hits 2-5 times in one turn."),
    PokemonMove("Tail Whip", "Normal", "Status", None, 100, 30, "Lowers opponent's Defense."),
    PokemonMove("Tailwind", "Flying", "Status", None, None, 15, "Doubles the Speed of all allies for 4 turns."),
    PokemonMove("Take Down", "Normal", "Physical", 90, 85, 20, "User receives recoil damage."),
    PokemonMove("Tar Shot", "Rock", "Status", None, 100, 15, "Lowers opponent's Speed and makes them weaker to Fire moves."),
    PokemonMove("Taunt", "Dark", "Status", None, 100, 20, "Prevents opponent from using Status moves for 3 turns."),
    PokemonMove("Tearful Look", "Normal", "Status", None, None, 20, "Lowers opponent's Attack and Special Attack."),
    PokemonMove("Techno Blast", "Normal", "Special", 120, 100, 5, "Type changes based on the Drive held."),
    PokemonMove("Teeter Dance", "Normal", "Status", None, 100, 20, "Confuses all Pokémon in battle."),
    PokemonMove("Teleport", "Psychic", "Status", None, None, 20, "Switches out the user."),
    PokemonMove("Terrain Pulse", "Normal", "Special", 50, 100, 10, "Power and type depend on the terrain."),
    PokemonMove("Thief", "Dark", "Physical", 60, 100, 25, "Steals opponent's held item."),
    PokemonMove("Thousand Arrows", "Ground", "Physical", 90, 100, 10, "Hits Flying-type Pokémon and knocks them down."),
    PokemonMove("Thousand Waves", "Ground", "Physical", 90, 100, 10, "Prevents opponent from escaping."),
    PokemonMove("Thrash", "Normal", "Physical", 120, 100, 10, "User attacks for 2-3 turns then becomes confused."),
    PokemonMove("Throat Chop", "Dark", "Physical", 80, 100, 15, "Prevents opponent from using sound-based moves for 2 turns."),
    PokemonMove("Thunder", "Electric", "Special", 110, 70, 10, "May paralyze opponent."),
    PokemonMove("Thunder Fang", "Electric", "Physical", 65, 95, 15, "May cause flinching or paralyze opponent."),
    PokemonMove("Thunder Punch", "Electric", "Physical", 75, 100, 15, "May paralyze opponent."),
    PokemonMove("Thunder Shock", "Electric", "Special", 40, 100, 30, "May paralyze opponent."),
    PokemonMove("Thunder Wave", "Electric", "Status", None, 90, 20, "Paralyzes opponent."),
    PokemonMove("Thunderbolt", "Electric", "Special", 90, 100, 15, "May paralyze opponent."),
    PokemonMove("Tickle", "Normal", "Status", None, 100, 20, "Lowers opponent's Attack and Defense."),
    PokemonMove("Topsy-Turvy", "Dark", "Status", None, None, 20, "Reverses all stat changes affecting the target."),
    PokemonMove("Torch Song", "Fire", "Special", 80, 100, 10, "Raises user's Special Attack."),
    PokemonMove("Toxic", "Poison", "Status", None, 90, 10, "Badly poisons opponent."),
    PokemonMove("Toxic Spikes", "Poison", "Status", None, None, 20, "Poisons opponents switching into battle."),
    PokemonMove("Transform", "Normal", "Status", None, None, 10, "User takes on the form and stats of the opponent."),
    PokemonMove("Tri Attack", "Normal", "Special", 80, 100, 10, "May paralyze, burn, or freeze opponent."),
    PokemonMove("Trick", "Psychic", "Status", None, 100, 10, "Swaps held items with the opponent."),
    PokemonMove("Trick Room", "Psychic", "Status", None, None, 5, "Slower Pokémon move first for 5 turns."),
    PokemonMove("Triple Axel", "Ice", "Physical", 20, 90, 10, "Hits 1-3 times in one turn, power increases with each hit."),
    PokemonMove("Triple Kick", "Fighting", "Physical", 10, 90, 10, "Hits 1-3 times in one turn, power increases with each hit."),
    PokemonMove("Trop Kick", "Grass", "Physical", 70, 100, 15, "Lowers opponent's Attack."),
    PokemonMove("Trump Card", "Normal", "Special", None, None, 5, "Power increases as PP decreases."),
    PokemonMove("Twineedle", "Bug", "Physical", 25, 100, 20, "Hits twice. May poison opponent."),
    PokemonMove("Twinkle Tackle", "Fairy", "Special", None, None, 1, "Fairy-type Z-Move."),
    PokemonMove("Twister", "Dragon", "Special", 40, 100, 20, "May cause flinching. Hits Pokémon using Fly or Bounce."),
    PokemonMove("U-turn", "Bug", "Physical", 70, 100, 20, "User switches out after attacking."),
    PokemonMove("Uproar", "Normal", "Special", 90, 100, 10, "User attacks for 3 turns and prevents sleep."),
    PokemonMove("V-create", "Fire", "Physical", 180, 95, 5, "Lowers user's Defense, Special Defense, and Speed."),
    PokemonMove("Vacuum Wave", "Fighting", "Special", 40, 100, 30, "User attacks first."),
    PokemonMove("Venom Drench", "Poison", "Status", None, 100, 20, "Lowers opponent's Attack, Special Attack, and Speed if poisoned."),
    PokemonMove("Venoshock", "Poison", "Special", 65, 100, 10, "Power doubles if opponent is poisoned."),
    PokemonMove("Vine Whip", "Grass", "Physical", 45, 100, 25, None),
    PokemonMove("Vise Grip", "Normal", "Physical", 55, 100, 30, None),
    PokemonMove("Vital Throw", "Fighting", "Physical", 70, None, 10, "User attacks last, but never misses."),
    PokemonMove("Volt Switch", "Electric", "Special", 70, 100, 20, "User switches out after attacking."),
    PokemonMove("Volt Tackle", "Electric", "Physical", 120, 100, 15, "User receives recoil damage. May paralyze opponent."),
    PokemonMove("Wake-Up Slap", "Fighting", "Physical", 70, 100, 10, "Power doubles if opponent is asleep, but wakes it up."),
    PokemonMove("Water Gun", "Water", "Special", 40, 100, 25, None),
    PokemonMove("Water Pledge", "Water", "Special", 80, 100, 10, "Added effects appear if combined with Grass Pledge or Fire Pledge."),
    PokemonMove("Water Pulse", "Water", "Special", 60, 100, 20, "May confuse opponent."),
    PokemonMove("Water Shuriken", "Water", "Special", 15, 100, 20, "Hits 2-5 times in one turn. User attacks first."),
    PokemonMove("Water Sport", "Water", "Status", None, None, 15, "Weakens the power of Fire-type moves."),
    PokemonMove("Water Spout", "Water", "Special", 150, 100, 5, "Power decreases as user's HP decreases."),
    PokemonMove("Waterfall", "Water", "Physical", 80, 100, 15, "May cause flinching."),
    PokemonMove("Weather Ball", "Normal", "Special", 50, 100, 10, "Move's type and power change with the weather."),
    PokemonMove("Whirlpool", "Water", "Special", 35, 85, 15, "Traps opponent, damaging it for 4-5 turns."),
    PokemonMove("Whirlwind", "Normal", "Status", None, None, 20, "Forces opponent to switch Pokémon."),
    PokemonMove("Wide Guard", "Rock", "Status", None, None, 10, "Protects team from multi-target moves."),
    PokemonMove("Wild Charge", "Electric", "Physical", 90, 100, 15, "User receives recoil damage."),
    PokemonMove("Will-O-Wisp", "Fire", "Status", None, 85, 15, "Burns opponent."),
    PokemonMove("Wing Attack", "Flying", "Physical", 60, 100, 35, None),
    PokemonMove("Wish", "Normal", "Status", None, None, 10, "Restores HP next turn."),
    PokemonMove("Withdraw", "Water", "Status", None, None, 40, "Raises user's Defense."),
    PokemonMove("Wonder Room", "Psychic", "Status", None, None, 10, "Swaps all Pokémon's Defense and Special Defense for 5 turns."),
    PokemonMove("Wood Hammer", "Grass", "Physical", 120, 100, 15, "User receives recoil damage."),
    PokemonMove("Work Up", "Normal", "Status", None, None, 30, "Raises user's Attack and Special Attack."),
    PokemonMove("Worry Seed", "Grass", "Status", None, 100, 10, "Changes opponent's Ability to Insomnia."),
    PokemonMove("Wrap", "Normal", "Physical", 15, 90, 20, "Traps opponent, damaging it for 4-5 turns."),
    PokemonMove("Wring Out", "Normal", "Special", None, 100, 5, "The higher the opponent's HP, the more damage caused."),
    PokemonMove("X-Scissor", "Bug", "Physical", 80, 100, 15, None),
    PokemonMove("Yawn", "Normal", "Status", None, None, 10, "Puts opponent to sleep next turn."),
    PokemonMove("Zap Cannon", "Electric", "Special", 120, 50, 5, "Paralyzes opponent."),
    PokemonMove("Zen Headbutt", "Psychic", "Physical", 80, 90, 15, "May cause flinching."),
    PokemonMove("Zing Zap", "Electric", "Physical", 80, 100, 10, "May cause flinching."),
    PokemonMove("Zippy Zap", "Electric", "Physical", 50, 100, 15, "Always results in a critical hit. User attacks first."),
    PokemonMove("Zygarde", "Dragon", "Status", None, None, 10, "User becomes Zygarde Complete if at 50% HP or less."),]

# Imprimindo todos os movimentos
for move in moves:
#     print(move)
	